// <auto-generated>
// This code was generated by a tool.
// LinqToWmi.ClassGenerator Version: 1.0.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if  the code is regenerated.
// </auto-generated>
namespace WmiEntities {
    using System;
    using System.Linq;
    using LinqToWmi.Core.WMI;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("LinqToWmi.ClassGenerator", "1.0.0.0")]
    public class Win32_PerfFormattedData_PerfOS_Memory {
        
        private ulong _availableBytes;
        
        private ulong _availableKBytes;
        
        private ulong _availableMBytes;
        
        private ulong _cacheBytes;
        
        private ulong _cacheBytesPeak;
        
        private uint _cacheFaultsPersec;
        
        private string _caption;
        
        private ulong _commitLimit;
        
        private ulong _committedBytes;
        
        private uint _demandZeroFaultsPersec;
        
        private string _description;
        
        private uint _freeSystemPageTableEntries;
        
        private ulong _frequency_Object;
        
        private ulong _frequency_PerfTime;
        
        private ulong _frequency_Sys100NS;
        
        private string _name;
        
        private uint _pageFaultsPersec;
        
        private uint _pageReadsPersec;
        
        private uint _pagesInputPersec;
        
        private uint _pagesOutputPersec;
        
        private uint _pagesPersec;
        
        private uint _pageWritesPersec;
        
        private uint _percentCommittedBytesInUse;
        
        private uint _poolNonpagedAllocs;
        
        private ulong _poolNonpagedBytes;
        
        private uint _poolPagedAllocs;
        
        private ulong _poolPagedBytes;
        
        private ulong _poolPagedResidentBytes;
        
        private ulong _systemCacheResidentBytes;
        
        private ulong _systemCodeResidentBytes;
        
        private ulong _systemCodeTotalBytes;
        
        private ulong _systemDriverResidentBytes;
        
        private ulong _systemDriverTotalBytes;
        
        private ulong _timestamp_Object;
        
        private ulong _timestamp_PerfTime;
        
        private ulong _timestamp_Sys100NS;
        
        private uint _transitionFaultsPersec;
        
        private uint _writeCopiesPersec;
        
        /// <summary>
        /// Represents the property AvailableBytes
        /// </summary>
        public virtual ulong AvailableBytes {
            get {
                return this._availableBytes;
            }
            set {
                this._availableBytes = value;
            }
        }
        
        /// <summary>
        /// Represents the property AvailableKBytes
        /// </summary>
        public virtual ulong AvailableKBytes {
            get {
                return this._availableKBytes;
            }
            set {
                this._availableKBytes = value;
            }
        }
        
        /// <summary>
        /// Represents the property AvailableMBytes
        /// </summary>
        public virtual ulong AvailableMBytes {
            get {
                return this._availableMBytes;
            }
            set {
                this._availableMBytes = value;
            }
        }
        
        /// <summary>
        /// Represents the property CacheBytes
        /// </summary>
        public virtual ulong CacheBytes {
            get {
                return this._cacheBytes;
            }
            set {
                this._cacheBytes = value;
            }
        }
        
        /// <summary>
        /// Represents the property CacheBytesPeak
        /// </summary>
        public virtual ulong CacheBytesPeak {
            get {
                return this._cacheBytesPeak;
            }
            set {
                this._cacheBytesPeak = value;
            }
        }
        
        /// <summary>
        /// Represents the property CacheFaultsPersec
        /// </summary>
        public virtual uint CacheFaultsPersec {
            get {
                return this._cacheFaultsPersec;
            }
            set {
                this._cacheFaultsPersec = value;
            }
        }
        
        /// <summary>
        /// Represents the property Caption
        /// </summary>
        public virtual string Caption {
            get {
                return this._caption;
            }
            set {
                this._caption = value;
            }
        }
        
        /// <summary>
        /// Represents the property CommitLimit
        /// </summary>
        public virtual ulong CommitLimit {
            get {
                return this._commitLimit;
            }
            set {
                this._commitLimit = value;
            }
        }
        
        /// <summary>
        /// Represents the property CommittedBytes
        /// </summary>
        public virtual ulong CommittedBytes {
            get {
                return this._committedBytes;
            }
            set {
                this._committedBytes = value;
            }
        }
        
        /// <summary>
        /// Represents the property DemandZeroFaultsPersec
        /// </summary>
        public virtual uint DemandZeroFaultsPersec {
            get {
                return this._demandZeroFaultsPersec;
            }
            set {
                this._demandZeroFaultsPersec = value;
            }
        }
        
        /// <summary>
        /// Represents the property Description
        /// </summary>
        public virtual string Description {
            get {
                return this._description;
            }
            set {
                this._description = value;
            }
        }
        
        /// <summary>
        /// Represents the property FreeSystemPageTableEntries
        /// </summary>
        public virtual uint FreeSystemPageTableEntries {
            get {
                return this._freeSystemPageTableEntries;
            }
            set {
                this._freeSystemPageTableEntries = value;
            }
        }
        
        /// <summary>
        /// Represents the property Frequency_Object
        /// </summary>
        public virtual ulong Frequency_Object {
            get {
                return this._frequency_Object;
            }
            set {
                this._frequency_Object = value;
            }
        }
        
        /// <summary>
        /// Represents the property Frequency_PerfTime
        /// </summary>
        public virtual ulong Frequency_PerfTime {
            get {
                return this._frequency_PerfTime;
            }
            set {
                this._frequency_PerfTime = value;
            }
        }
        
        /// <summary>
        /// Represents the property Frequency_Sys100NS
        /// </summary>
        public virtual ulong Frequency_Sys100NS {
            get {
                return this._frequency_Sys100NS;
            }
            set {
                this._frequency_Sys100NS = value;
            }
        }
        
        /// <summary>
        /// Represents the property Name
        /// </summary>
        public virtual string Name {
            get {
                return this._name;
            }
            set {
                this._name = value;
            }
        }
        
        /// <summary>
        /// Represents the property PageFaultsPersec
        /// </summary>
        public virtual uint PageFaultsPersec {
            get {
                return this._pageFaultsPersec;
            }
            set {
                this._pageFaultsPersec = value;
            }
        }
        
        /// <summary>
        /// Represents the property PageReadsPersec
        /// </summary>
        public virtual uint PageReadsPersec {
            get {
                return this._pageReadsPersec;
            }
            set {
                this._pageReadsPersec = value;
            }
        }
        
        /// <summary>
        /// Represents the property PagesInputPersec
        /// </summary>
        public virtual uint PagesInputPersec {
            get {
                return this._pagesInputPersec;
            }
            set {
                this._pagesInputPersec = value;
            }
        }
        
        /// <summary>
        /// Represents the property PagesOutputPersec
        /// </summary>
        public virtual uint PagesOutputPersec {
            get {
                return this._pagesOutputPersec;
            }
            set {
                this._pagesOutputPersec = value;
            }
        }
        
        /// <summary>
        /// Represents the property PagesPersec
        /// </summary>
        public virtual uint PagesPersec {
            get {
                return this._pagesPersec;
            }
            set {
                this._pagesPersec = value;
            }
        }
        
        /// <summary>
        /// Represents the property PageWritesPersec
        /// </summary>
        public virtual uint PageWritesPersec {
            get {
                return this._pageWritesPersec;
            }
            set {
                this._pageWritesPersec = value;
            }
        }
        
        /// <summary>
        /// Represents the property PercentCommittedBytesInUse
        /// </summary>
        public virtual uint PercentCommittedBytesInUse {
            get {
                return this._percentCommittedBytesInUse;
            }
            set {
                this._percentCommittedBytesInUse = value;
            }
        }
        
        /// <summary>
        /// Represents the property PoolNonpagedAllocs
        /// </summary>
        public virtual uint PoolNonpagedAllocs {
            get {
                return this._poolNonpagedAllocs;
            }
            set {
                this._poolNonpagedAllocs = value;
            }
        }
        
        /// <summary>
        /// Represents the property PoolNonpagedBytes
        /// </summary>
        public virtual ulong PoolNonpagedBytes {
            get {
                return this._poolNonpagedBytes;
            }
            set {
                this._poolNonpagedBytes = value;
            }
        }
        
        /// <summary>
        /// Represents the property PoolPagedAllocs
        /// </summary>
        public virtual uint PoolPagedAllocs {
            get {
                return this._poolPagedAllocs;
            }
            set {
                this._poolPagedAllocs = value;
            }
        }
        
        /// <summary>
        /// Represents the property PoolPagedBytes
        /// </summary>
        public virtual ulong PoolPagedBytes {
            get {
                return this._poolPagedBytes;
            }
            set {
                this._poolPagedBytes = value;
            }
        }
        
        /// <summary>
        /// Represents the property PoolPagedResidentBytes
        /// </summary>
        public virtual ulong PoolPagedResidentBytes {
            get {
                return this._poolPagedResidentBytes;
            }
            set {
                this._poolPagedResidentBytes = value;
            }
        }
        
        /// <summary>
        /// Represents the property SystemCacheResidentBytes
        /// </summary>
        public virtual ulong SystemCacheResidentBytes {
            get {
                return this._systemCacheResidentBytes;
            }
            set {
                this._systemCacheResidentBytes = value;
            }
        }
        
        /// <summary>
        /// Represents the property SystemCodeResidentBytes
        /// </summary>
        public virtual ulong SystemCodeResidentBytes {
            get {
                return this._systemCodeResidentBytes;
            }
            set {
                this._systemCodeResidentBytes = value;
            }
        }
        
        /// <summary>
        /// Represents the property SystemCodeTotalBytes
        /// </summary>
        public virtual ulong SystemCodeTotalBytes {
            get {
                return this._systemCodeTotalBytes;
            }
            set {
                this._systemCodeTotalBytes = value;
            }
        }
        
        /// <summary>
        /// Represents the property SystemDriverResidentBytes
        /// </summary>
        public virtual ulong SystemDriverResidentBytes {
            get {
                return this._systemDriverResidentBytes;
            }
            set {
                this._systemDriverResidentBytes = value;
            }
        }
        
        /// <summary>
        /// Represents the property SystemDriverTotalBytes
        /// </summary>
        public virtual ulong SystemDriverTotalBytes {
            get {
                return this._systemDriverTotalBytes;
            }
            set {
                this._systemDriverTotalBytes = value;
            }
        }
        
        /// <summary>
        /// Represents the property Timestamp_Object
        /// </summary>
        public virtual ulong Timestamp_Object {
            get {
                return this._timestamp_Object;
            }
            set {
                this._timestamp_Object = value;
            }
        }
        
        /// <summary>
        /// Represents the property Timestamp_PerfTime
        /// </summary>
        public virtual ulong Timestamp_PerfTime {
            get {
                return this._timestamp_PerfTime;
            }
            set {
                this._timestamp_PerfTime = value;
            }
        }
        
        /// <summary>
        /// Represents the property Timestamp_Sys100NS
        /// </summary>
        public virtual ulong Timestamp_Sys100NS {
            get {
                return this._timestamp_Sys100NS;
            }
            set {
                this._timestamp_Sys100NS = value;
            }
        }
        
        /// <summary>
        /// Represents the property TransitionFaultsPersec
        /// </summary>
        public virtual uint TransitionFaultsPersec {
            get {
                return this._transitionFaultsPersec;
            }
            set {
                this._transitionFaultsPersec = value;
            }
        }
        
        /// <summary>
        /// Represents the property WriteCopiesPersec
        /// </summary>
        public virtual uint WriteCopiesPersec {
            get {
                return this._writeCopiesPersec;
            }
            set {
                this._writeCopiesPersec = value;
            }
        }
    }
}
