// <auto-generated>
// This code was generated by a tool.
// LinqToWmi.ClassGenerator Version: 1.0.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if  the code is regenerated.
// </auto-generated>
namespace WmiEntities
{
    using System;
    using System.Linq;
    using LinqToWmi.Core.WMI;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("LinqToWmi.ClassGenerator", "1.0.0.0")]
    public class Win32_ComputerSystem
    {

        private ushort _adminPasswordStatus;

        private bool _automaticResetBootOption;

        private bool _automaticResetCapability;

        private ushort _bootOptionOnLimit;

        private ushort _bootOptionOnWatchDog;

        private bool _bootROMSupported;

        private string _bootupState;

        private string _caption;

        private ushort _chassisBootupState;

        private string _creationClassName;

        private short _currentTimeZone;

        private bool _daylightInEffect;

        private string _description;

        private string _domain;

        private ushort _domainRole;

        private bool _enableDaylightSavingsTime;

        private ushort _frontPanelResetStatus;

        private bool _infraredSupported;

        private string[] _initialLoadInfo;

        private System.DateTime _installDate;

        private ushort _keyboardPasswordStatus;

        private string _lastLoadInfo;

        private string _manufacturer;

        private string _model;

        private string _name;

        private string _nameFormat;

        private bool _networkServerModeEnabled;

        private uint _numberOfProcessors;

        private byte[] _oEMLogoBitmap;

        private string[] _oEMStringArray;

        private bool _partOfDomain;

        private long _pauseAfterReset;

        private ushort[] _powerManagementCapabilities;

        private bool _powerManagementSupported;

        private ushort _powerOnPasswordStatus;

        private ushort _powerState;

        private ushort _powerSupplyState;

        private string _primaryOwnerContact;

        private string _primaryOwnerName;

        private ushort _resetCapability;

        private short _resetCount;

        private short _resetLimit;

        private string[] _roles;

        private string _status;

        private string[] _supportContactDescription;

        private ushort _systemStartupDelay;

        private string[] _systemStartupOptions;

        private byte _systemStartupSetting;

        private string _systemType;

        private ushort _thermalState;

        private ulong _totalPhysicalMemory;

        private string _userName;

        private ushort _wakeUpType;

        private string _workgroup;

        /// <summary>
        /// Represents the property AdminPasswordStatus
        /// </summary>
        public virtual ushort AdminPasswordStatus
        {
            get
            {
                return this._adminPasswordStatus;
            }
            set
            {
                this._adminPasswordStatus = value;
            }
        }

        /// <summary>
        /// Represents the property AutomaticResetBootOption
        /// </summary>
        public virtual bool AutomaticResetBootOption
        {
            get
            {
                return this._automaticResetBootOption;
            }
            set
            {
                this._automaticResetBootOption = value;
            }
        }

        /// <summary>
        /// Represents the property AutomaticResetCapability
        /// </summary>
        public virtual bool AutomaticResetCapability
        {
            get
            {
                return this._automaticResetCapability;
            }
            set
            {
                this._automaticResetCapability = value;
            }
        }

        /// <summary>
        /// Represents the property BootOptionOnLimit
        /// </summary>
        public virtual ushort BootOptionOnLimit
        {
            get
            {
                return this._bootOptionOnLimit;
            }
            set
            {
                this._bootOptionOnLimit = value;
            }
        }

        /// <summary>
        /// Represents the property BootOptionOnWatchDog
        /// </summary>
        public virtual ushort BootOptionOnWatchDog
        {
            get
            {
                return this._bootOptionOnWatchDog;
            }
            set
            {
                this._bootOptionOnWatchDog = value;
            }
        }

        /// <summary>
        /// Represents the property BootROMSupported
        /// </summary>
        public virtual bool BootROMSupported
        {
            get
            {
                return this._bootROMSupported;
            }
            set
            {
                this._bootROMSupported = value;
            }
        }

        /// <summary>
        /// Represents the property BootupState
        /// </summary>
        public virtual string BootupState
        {
            get
            {
                return this._bootupState;
            }
            set
            {
                this._bootupState = value;
            }
        }

        /// <summary>
        /// Represents the property Caption
        /// </summary>
        public virtual string Caption
        {
            get
            {
                return this._caption;
            }
            set
            {
                this._caption = value;
            }
        }

        /// <summary>
        /// Represents the property ChassisBootupState
        /// </summary>
        public virtual ushort ChassisBootupState
        {
            get
            {
                return this._chassisBootupState;
            }
            set
            {
                this._chassisBootupState = value;
            }
        }

        /// <summary>
        /// Represents the property CreationClassName
        /// </summary>
        public virtual string CreationClassName
        {
            get
            {
                return this._creationClassName;
            }
            set
            {
                this._creationClassName = value;
            }
        }

        /// <summary>
        /// Represents the property CurrentTimeZone
        /// </summary>
        public virtual short CurrentTimeZone
        {
            get
            {
                return this._currentTimeZone;
            }
            set
            {
                this._currentTimeZone = value;
            }
        }

        /// <summary>
        /// Represents the property DaylightInEffect
        /// </summary>
        public virtual bool DaylightInEffect
        {
            get
            {
                return this._daylightInEffect;
            }
            set
            {
                this._daylightInEffect = value;
            }
        }

        /// <summary>
        /// Represents the property Description
        /// </summary>
        public virtual string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                this._description = value;
            }
        }

        /// <summary>
        /// Represents the property Domain
        /// </summary>
        public virtual string Domain
        {
            get
            {
                return this._domain;
            }
            set
            {
                this._domain = value;
            }
        }

        /// <summary>
        /// Represents the property DomainRole
        /// </summary>
        public virtual ushort DomainRole
        {
            get
            {
                return this._domainRole;
            }
            set
            {
                this._domainRole = value;
            }
        }

        /// <summary>
        /// Represents the property EnableDaylightSavingsTime
        /// </summary>
        public virtual bool EnableDaylightSavingsTime
        {
            get
            {
                return this._enableDaylightSavingsTime;
            }
            set
            {
                this._enableDaylightSavingsTime = value;
            }
        }

        /// <summary>
        /// Represents the property FrontPanelResetStatus
        /// </summary>
        public virtual ushort FrontPanelResetStatus
        {
            get
            {
                return this._frontPanelResetStatus;
            }
            set
            {
                this._frontPanelResetStatus = value;
            }
        }

        /// <summary>
        /// Represents the property InfraredSupported
        /// </summary>
        public virtual bool InfraredSupported
        {
            get
            {
                return this._infraredSupported;
            }
            set
            {
                this._infraredSupported = value;
            }
        }

        /// <summary>
        /// Represents the property InitialLoadInfo
        /// </summary>
        public virtual string[] InitialLoadInfo
        {
            get
            {
                return this._initialLoadInfo;
            }
            set
            {
                this._initialLoadInfo = value;
            }
        }

        /// <summary>
        /// Represents the property InstallDate
        /// </summary>
        public virtual System.DateTime InstallDate
        {
            get
            {
                return this._installDate;
            }
            set
            {
                this._installDate = value;
            }
        }

        /// <summary>
        /// Represents the property KeyboardPasswordStatus
        /// </summary>
        public virtual ushort KeyboardPasswordStatus
        {
            get
            {
                return this._keyboardPasswordStatus;
            }
            set
            {
                this._keyboardPasswordStatus = value;
            }
        }

        /// <summary>
        /// Represents the property LastLoadInfo
        /// </summary>
        public virtual string LastLoadInfo
        {
            get
            {
                return this._lastLoadInfo;
            }
            set
            {
                this._lastLoadInfo = value;
            }
        }

        /// <summary>
        /// Represents the property Manufacturer
        /// </summary>
        public virtual string Manufacturer
        {
            get
            {
                return this._manufacturer;
            }
            set
            {
                this._manufacturer = value;
            }
        }

        /// <summary>
        /// Represents the property Model
        /// </summary>
        public virtual string Model
        {
            get
            {
                return this._model;
            }
            set
            {
                this._model = value;
            }
        }

        /// <summary>
        /// Represents the property Name
        /// </summary>
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }

        /// <summary>
        /// Represents the property NameFormat
        /// </summary>
        public virtual string NameFormat
        {
            get
            {
                return this._nameFormat;
            }
            set
            {
                this._nameFormat = value;
            }
        }

        /// <summary>
        /// Represents the property NetworkServerModeEnabled
        /// </summary>
        public virtual bool NetworkServerModeEnabled
        {
            get
            {
                return this._networkServerModeEnabled;
            }
            set
            {
                this._networkServerModeEnabled = value;
            }
        }

        /// <summary>
        /// Represents the property NumberOfProcessors
        /// </summary>
        public virtual uint NumberOfProcessors
        {
            get
            {
                return this._numberOfProcessors;
            }
            set
            {
                this._numberOfProcessors = value;
            }
        }

        /// <summary>
        /// Represents the property OEMLogoBitmap
        /// </summary>
        public virtual byte[] OEMLogoBitmap
        {
            get
            {
                return this._oEMLogoBitmap;
            }
            set
            {
                this._oEMLogoBitmap = value;
            }
        }

        /// <summary>
        /// Represents the property OEMStringArray
        /// </summary>
        public virtual string[] OEMStringArray
        {
            get
            {
                return this._oEMStringArray;
            }
            set
            {
                this._oEMStringArray = value;
            }
        }

        /// <summary>
        /// Represents the property PartOfDomain
        /// </summary>
        public virtual bool PartOfDomain
        {
            get
            {
                return this._partOfDomain;
            }
            set
            {
                this._partOfDomain = value;
            }
        }

        /// <summary>
        /// Represents the property PauseAfterReset
        /// </summary>
        public virtual long PauseAfterReset
        {
            get
            {
                return this._pauseAfterReset;
            }
            set
            {
                this._pauseAfterReset = value;
            }
        }

        /// <summary>
        /// Represents the property PowerManagementCapabilities
        /// </summary>
        public virtual ushort[] PowerManagementCapabilities
        {
            get
            {
                return this._powerManagementCapabilities;
            }
            set
            {
                this._powerManagementCapabilities = value;
            }
        }

        /// <summary>
        /// Represents the property PowerManagementSupported
        /// </summary>
        public virtual bool PowerManagementSupported
        {
            get
            {
                return this._powerManagementSupported;
            }
            set
            {
                this._powerManagementSupported = value;
            }
        }

        /// <summary>
        /// Represents the property PowerOnPasswordStatus
        /// </summary>
        public virtual ushort PowerOnPasswordStatus
        {
            get
            {
                return this._powerOnPasswordStatus;
            }
            set
            {
                this._powerOnPasswordStatus = value;
            }
        }

        /// <summary>
        /// Represents the property PowerState
        /// </summary>
        public virtual ushort PowerState
        {
            get
            {
                return this._powerState;
            }
            set
            {
                this._powerState = value;
            }
        }

        /// <summary>
        /// Represents the property PowerSupplyState
        /// </summary>
        public virtual ushort PowerSupplyState
        {
            get
            {
                return this._powerSupplyState;
            }
            set
            {
                this._powerSupplyState = value;
            }
        }

        /// <summary>
        /// Represents the property PrimaryOwnerContact
        /// </summary>
        public virtual string PrimaryOwnerContact
        {
            get
            {
                return this._primaryOwnerContact;
            }
            set
            {
                this._primaryOwnerContact = value;
            }
        }

        /// <summary>
        /// Represents the property PrimaryOwnerName
        /// </summary>
        public virtual string PrimaryOwnerName
        {
            get
            {
                return this._primaryOwnerName;
            }
            set
            {
                this._primaryOwnerName = value;
            }
        }

        /// <summary>
        /// Represents the property ResetCapability
        /// </summary>
        public virtual ushort ResetCapability
        {
            get
            {
                return this._resetCapability;
            }
            set
            {
                this._resetCapability = value;
            }
        }

        /// <summary>
        /// Represents the property ResetCount
        /// </summary>
        public virtual short ResetCount
        {
            get
            {
                return this._resetCount;
            }
            set
            {
                this._resetCount = value;
            }
        }

        /// <summary>
        /// Represents the property ResetLimit
        /// </summary>
        public virtual short ResetLimit
        {
            get
            {
                return this._resetLimit;
            }
            set
            {
                this._resetLimit = value;
            }
        }

        /// <summary>
        /// Represents the property Roles
        /// </summary>
        public virtual string[] Roles
        {
            get
            {
                return this._roles;
            }
            set
            {
                this._roles = value;
            }
        }

        /// <summary>
        /// Represents the property Status
        /// </summary>
        public virtual string Status
        {
            get
            {
                return this._status;
            }
            set
            {
                this._status = value;
            }
        }

        /// <summary>
        /// Represents the property SupportContactDescription
        /// </summary>
        public virtual string[] SupportContactDescription
        {
            get
            {
                return this._supportContactDescription;
            }
            set
            {
                this._supportContactDescription = value;
            }
        }

        /// <summary>
        /// Represents the property SystemStartupDelay
        /// </summary>
        public virtual ushort SystemStartupDelay
        {
            get
            {
                return this._systemStartupDelay;
            }
            set
            {
                this._systemStartupDelay = value;
            }
        }

        /// <summary>
        /// Represents the property SystemStartupOptions
        /// </summary>
        public virtual string[] SystemStartupOptions
        {
            get
            {
                return this._systemStartupOptions;
            }
            set
            {
                this._systemStartupOptions = value;
            }
        }

        /// <summary>
        /// Represents the property SystemStartupSetting
        /// </summary>
        public virtual byte SystemStartupSetting
        {
            get
            {
                return this._systemStartupSetting;
            }
            set
            {
                this._systemStartupSetting = value;
            }
        }

        /// <summary>
        /// Represents the property SystemType
        /// </summary>
        public virtual string SystemType
        {
            get
            {
                return this._systemType;
            }
            set
            {
                this._systemType = value;
            }
        }

        /// <summary>
        /// Represents the property ThermalState
        /// </summary>
        public virtual ushort ThermalState
        {
            get
            {
                return this._thermalState;
            }
            set
            {
                this._thermalState = value;
            }
        }

        /// <summary>
        /// Represents the property TotalPhysicalMemory
        /// </summary>
        public virtual ulong TotalPhysicalMemory
        {
            get
            {
                return this._totalPhysicalMemory;
            }
            set
            {
                this._totalPhysicalMemory = value;
            }
        }

        /// <summary>
        /// Represents the property UserName
        /// </summary>
        public virtual string UserName
        {
            get
            {
                return this._userName;
            }
            set
            {
                this._userName = value;
            }
        }

        /// <summary>
        /// Represents the property WakeUpType
        /// </summary>
        public virtual ushort WakeUpType
        {
            get
            {
                return this._wakeUpType;
            }
            set
            {
                this._wakeUpType = value;
            }
        }

        /// <summary>
        /// Represents the property Workgroup
        /// </summary>
        public virtual string Workgroup
        {
            get
            {
                return this._workgroup;
            }
            set
            {
                this._workgroup = value;
            }
        }
    }
}
