
// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>
using System;  
namespace ContinuousLinq.Expressions
{
	public static class Partials
	{
	
		 
		public static Func<T1, TReturn> Partial<TC1, T1, TReturn>(this Func<TC1, T1, TReturn> function, TC1 tc1)
		{
			return (t1) => function(tc1, t1);
		}
		 
		public static Func<T1, TReturn> Partial<TC1, TC2, T1, TReturn>(this Func<TC1, TC2, T1, TReturn> function, TC1 tc1, TC2 tc2)
		{
			return (t1) => function(tc1, tc2, t1);
		}
		 
		public static Func<T1, TReturn> Partial<TC1, TC2, TC3, T1, TReturn>(this Func<TC1, TC2, TC3, T1, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3)
		{
			return (t1) => function(tc1, tc2, tc3, t1);
		}
		 
		public static Func<T1, TReturn> Partial<TC1, TC2, TC3, TC4, T1, TReturn>(this Func<TC1, TC2, TC3, TC4, T1, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4)
		{
			return (t1) => function(tc1, tc2, tc3, tc4, t1);
		}
		 
		public static Func<T1, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, T1, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, T1, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5)
		{
			return (t1) => function(tc1, tc2, tc3, tc4, tc5, t1);
		}
		 
		public static Func<T1, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, T1, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, T1, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6)
		{
			return (t1) => function(tc1, tc2, tc3, tc4, tc5, tc6, t1);
		}
		 
		public static Func<T1, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7)
		{
			return (t1) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, t1);
		}
		 
		public static Func<T1, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, T1, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, T1, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8)
		{
			return (t1) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, t1);
		}
		 
		public static Func<T1, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, T1, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, T1, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9)
		{
			return (t1) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, t1);
		}
		 
		public static Func<T1, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, T1, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, T1, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10)
		{
			return (t1) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, t1);
		}
		 
		public static Func<T1, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, T1, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, T1, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11)
		{
			return (t1) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, t1);
		}
		 
		public static Func<T1, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, T1, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, T1, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12)
		{
			return (t1) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, t1);
		}
		 
		public static Func<T1, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, T1, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, T1, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12, TC13 tc13)
		{
			return (t1) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, tc13, t1);
		}
		 
		public static Func<T1, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, T1, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, T1, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12, TC13 tc13, TC14 tc14)
		{
			return (t1) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, tc13, tc14, t1);
		}
		 
		public static Func<T1, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, TC15, T1, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, TC15, T1, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12, TC13 tc13, TC14 tc14, TC15 tc15)
		{
			return (t1) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, tc13, tc14, tc15, t1);
		}
		 
		public static Func<T1, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, TC15, TC16, T1, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, TC15, TC16, T1, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12, TC13 tc13, TC14 tc14, TC15 tc15, TC16 tc16)
		{
			return (t1) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, tc13, tc14, tc15, tc16, t1);
		}
		 
		public static Func<T1, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, TC15, TC16, TC17, T1, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, TC15, TC16, TC17, T1, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12, TC13 tc13, TC14 tc14, TC15 tc15, TC16 tc16, TC17 tc17)
		{
			return (t1) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, tc13, tc14, tc15, tc16, tc17, t1);
		}
		 
		public static Func<T1, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, TC15, TC16, TC17, TC18, T1, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, TC15, TC16, TC17, TC18, T1, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12, TC13 tc13, TC14 tc14, TC15 tc15, TC16 tc16, TC17 tc17, TC18 tc18)
		{
			return (t1) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, tc13, tc14, tc15, tc16, tc17, tc18, t1);
		}
		 
		public static Func<T1, T2, TReturn> Partial<TC1, T1, T2, TReturn>(this Func<TC1, T1, T2, TReturn> function, TC1 tc1)
		{
			return (t1, t2) => function(tc1, t1, t2);
		}
		 
		public static Func<T1, T2, TReturn> Partial<TC1, TC2, T1, T2, TReturn>(this Func<TC1, TC2, T1, T2, TReturn> function, TC1 tc1, TC2 tc2)
		{
			return (t1, t2) => function(tc1, tc2, t1, t2);
		}
		 
		public static Func<T1, T2, TReturn> Partial<TC1, TC2, TC3, T1, T2, TReturn>(this Func<TC1, TC2, TC3, T1, T2, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3)
		{
			return (t1, t2) => function(tc1, tc2, tc3, t1, t2);
		}
		 
		public static Func<T1, T2, TReturn> Partial<TC1, TC2, TC3, TC4, T1, T2, TReturn>(this Func<TC1, TC2, TC3, TC4, T1, T2, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4)
		{
			return (t1, t2) => function(tc1, tc2, tc3, tc4, t1, t2);
		}
		 
		public static Func<T1, T2, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, T1, T2, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, T1, T2, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5)
		{
			return (t1, t2) => function(tc1, tc2, tc3, tc4, tc5, t1, t2);
		}
		 
		public static Func<T1, T2, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6)
		{
			return (t1, t2) => function(tc1, tc2, tc3, tc4, tc5, tc6, t1, t2);
		}
		 
		public static Func<T1, T2, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, T2, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, T2, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7)
		{
			return (t1, t2) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, t1, t2);
		}
		 
		public static Func<T1, T2, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, T1, T2, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, T1, T2, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8)
		{
			return (t1, t2) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, t1, t2);
		}
		 
		public static Func<T1, T2, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, T1, T2, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, T1, T2, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9)
		{
			return (t1, t2) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, t1, t2);
		}
		 
		public static Func<T1, T2, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, T1, T2, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, T1, T2, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10)
		{
			return (t1, t2) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, t1, t2);
		}
		 
		public static Func<T1, T2, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, T1, T2, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, T1, T2, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11)
		{
			return (t1, t2) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, t1, t2);
		}
		 
		public static Func<T1, T2, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, T1, T2, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, T1, T2, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12)
		{
			return (t1, t2) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, t1, t2);
		}
		 
		public static Func<T1, T2, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, T1, T2, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, T1, T2, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12, TC13 tc13)
		{
			return (t1, t2) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, tc13, t1, t2);
		}
		 
		public static Func<T1, T2, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, T1, T2, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, T1, T2, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12, TC13 tc13, TC14 tc14)
		{
			return (t1, t2) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, tc13, tc14, t1, t2);
		}
		 
		public static Func<T1, T2, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, TC15, T1, T2, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, TC15, T1, T2, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12, TC13 tc13, TC14 tc14, TC15 tc15)
		{
			return (t1, t2) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, tc13, tc14, tc15, t1, t2);
		}
		 
		public static Func<T1, T2, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, TC15, TC16, T1, T2, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, TC15, TC16, T1, T2, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12, TC13 tc13, TC14 tc14, TC15 tc15, TC16 tc16)
		{
			return (t1, t2) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, tc13, tc14, tc15, tc16, t1, t2);
		}
		 
		public static Func<T1, T2, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, TC15, TC16, TC17, T1, T2, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, TC15, TC16, TC17, T1, T2, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12, TC13 tc13, TC14 tc14, TC15 tc15, TC16 tc16, TC17 tc17)
		{
			return (t1, t2) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, tc13, tc14, tc15, tc16, tc17, t1, t2);
		}
		 
		public static Func<T1, T2, T3, TReturn> Partial<TC1, T1, T2, T3, TReturn>(this Func<TC1, T1, T2, T3, TReturn> function, TC1 tc1)
		{
			return (t1, t2, t3) => function(tc1, t1, t2, t3);
		}
		 
		public static Func<T1, T2, T3, TReturn> Partial<TC1, TC2, T1, T2, T3, TReturn>(this Func<TC1, TC2, T1, T2, T3, TReturn> function, TC1 tc1, TC2 tc2)
		{
			return (t1, t2, t3) => function(tc1, tc2, t1, t2, t3);
		}
		 
		public static Func<T1, T2, T3, TReturn> Partial<TC1, TC2, TC3, T1, T2, T3, TReturn>(this Func<TC1, TC2, TC3, T1, T2, T3, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3)
		{
			return (t1, t2, t3) => function(tc1, tc2, tc3, t1, t2, t3);
		}
		 
		public static Func<T1, T2, T3, TReturn> Partial<TC1, TC2, TC3, TC4, T1, T2, T3, TReturn>(this Func<TC1, TC2, TC3, TC4, T1, T2, T3, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4)
		{
			return (t1, t2, t3) => function(tc1, tc2, tc3, tc4, t1, t2, t3);
		}
		 
		public static Func<T1, T2, T3, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5)
		{
			return (t1, t2, t3) => function(tc1, tc2, tc3, tc4, tc5, t1, t2, t3);
		}
		 
		public static Func<T1, T2, T3, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, T3, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, T3, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6)
		{
			return (t1, t2, t3) => function(tc1, tc2, tc3, tc4, tc5, tc6, t1, t2, t3);
		}
		 
		public static Func<T1, T2, T3, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, T2, T3, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, T2, T3, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7)
		{
			return (t1, t2, t3) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, t1, t2, t3);
		}
		 
		public static Func<T1, T2, T3, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, T1, T2, T3, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, T1, T2, T3, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8)
		{
			return (t1, t2, t3) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, t1, t2, t3);
		}
		 
		public static Func<T1, T2, T3, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, T1, T2, T3, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, T1, T2, T3, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9)
		{
			return (t1, t2, t3) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, t1, t2, t3);
		}
		 
		public static Func<T1, T2, T3, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, T1, T2, T3, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, T1, T2, T3, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10)
		{
			return (t1, t2, t3) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, t1, t2, t3);
		}
		 
		public static Func<T1, T2, T3, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, T1, T2, T3, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, T1, T2, T3, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11)
		{
			return (t1, t2, t3) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, t1, t2, t3);
		}
		 
		public static Func<T1, T2, T3, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, T1, T2, T3, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, T1, T2, T3, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12)
		{
			return (t1, t2, t3) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, t1, t2, t3);
		}
		 
		public static Func<T1, T2, T3, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, T1, T2, T3, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, T1, T2, T3, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12, TC13 tc13)
		{
			return (t1, t2, t3) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, tc13, t1, t2, t3);
		}
		 
		public static Func<T1, T2, T3, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, T1, T2, T3, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, T1, T2, T3, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12, TC13 tc13, TC14 tc14)
		{
			return (t1, t2, t3) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, tc13, tc14, t1, t2, t3);
		}
		 
		public static Func<T1, T2, T3, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, TC15, T1, T2, T3, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, TC15, T1, T2, T3, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12, TC13 tc13, TC14 tc14, TC15 tc15)
		{
			return (t1, t2, t3) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, tc13, tc14, tc15, t1, t2, t3);
		}
		 
		public static Func<T1, T2, T3, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, TC15, TC16, T1, T2, T3, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, TC15, TC16, T1, T2, T3, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12, TC13 tc13, TC14 tc14, TC15 tc15, TC16 tc16)
		{
			return (t1, t2, t3) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, tc13, tc14, tc15, tc16, t1, t2, t3);
		}
		 
		public static Func<T1, T2, T3, T4, TReturn> Partial<TC1, T1, T2, T3, T4, TReturn>(this Func<TC1, T1, T2, T3, T4, TReturn> function, TC1 tc1)
		{
			return (t1, t2, t3, t4) => function(tc1, t1, t2, t3, t4);
		}
		 
		public static Func<T1, T2, T3, T4, TReturn> Partial<TC1, TC2, T1, T2, T3, T4, TReturn>(this Func<TC1, TC2, T1, T2, T3, T4, TReturn> function, TC1 tc1, TC2 tc2)
		{
			return (t1, t2, t3, t4) => function(tc1, tc2, t1, t2, t3, t4);
		}
		 
		public static Func<T1, T2, T3, T4, TReturn> Partial<TC1, TC2, TC3, T1, T2, T3, T4, TReturn>(this Func<TC1, TC2, TC3, T1, T2, T3, T4, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3)
		{
			return (t1, t2, t3, t4) => function(tc1, tc2, tc3, t1, t2, t3, t4);
		}
		 
		public static Func<T1, T2, T3, T4, TReturn> Partial<TC1, TC2, TC3, TC4, T1, T2, T3, T4, TReturn>(this Func<TC1, TC2, TC3, TC4, T1, T2, T3, T4, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4)
		{
			return (t1, t2, t3, t4) => function(tc1, tc2, tc3, tc4, t1, t2, t3, t4);
		}
		 
		public static Func<T1, T2, T3, T4, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, T4, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, T4, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5)
		{
			return (t1, t2, t3, t4) => function(tc1, tc2, tc3, tc4, tc5, t1, t2, t3, t4);
		}
		 
		public static Func<T1, T2, T3, T4, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, T3, T4, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, T3, T4, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6)
		{
			return (t1, t2, t3, t4) => function(tc1, tc2, tc3, tc4, tc5, tc6, t1, t2, t3, t4);
		}
		 
		public static Func<T1, T2, T3, T4, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, T2, T3, T4, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, T2, T3, T4, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7)
		{
			return (t1, t2, t3, t4) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, t1, t2, t3, t4);
		}
		 
		public static Func<T1, T2, T3, T4, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, T1, T2, T3, T4, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, T1, T2, T3, T4, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8)
		{
			return (t1, t2, t3, t4) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, t1, t2, t3, t4);
		}
		 
		public static Func<T1, T2, T3, T4, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, T1, T2, T3, T4, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, T1, T2, T3, T4, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9)
		{
			return (t1, t2, t3, t4) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, t1, t2, t3, t4);
		}
		 
		public static Func<T1, T2, T3, T4, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, T1, T2, T3, T4, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, T1, T2, T3, T4, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10)
		{
			return (t1, t2, t3, t4) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, t1, t2, t3, t4);
		}
		 
		public static Func<T1, T2, T3, T4, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, T1, T2, T3, T4, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, T1, T2, T3, T4, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11)
		{
			return (t1, t2, t3, t4) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, t1, t2, t3, t4);
		}
		 
		public static Func<T1, T2, T3, T4, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, T1, T2, T3, T4, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, T1, T2, T3, T4, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12)
		{
			return (t1, t2, t3, t4) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, t1, t2, t3, t4);
		}
		 
		public static Func<T1, T2, T3, T4, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, T1, T2, T3, T4, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, T1, T2, T3, T4, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12, TC13 tc13)
		{
			return (t1, t2, t3, t4) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, tc13, t1, t2, t3, t4);
		}
		 
		public static Func<T1, T2, T3, T4, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, T1, T2, T3, T4, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, T1, T2, T3, T4, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12, TC13 tc13, TC14 tc14)
		{
			return (t1, t2, t3, t4) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, tc13, tc14, t1, t2, t3, t4);
		}
		 
		public static Func<T1, T2, T3, T4, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, TC15, T1, T2, T3, T4, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, TC15, T1, T2, T3, T4, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12, TC13 tc13, TC14 tc14, TC15 tc15)
		{
			return (t1, t2, t3, t4) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, tc13, tc14, tc15, t1, t2, t3, t4);
		}
		 
		public static Func<T1, T2, T3, T4, T5, TReturn> Partial<TC1, T1, T2, T3, T4, T5, TReturn>(this Func<TC1, T1, T2, T3, T4, T5, TReturn> function, TC1 tc1)
		{
			return (t1, t2, t3, t4, t5) => function(tc1, t1, t2, t3, t4, t5);
		}
		 
		public static Func<T1, T2, T3, T4, T5, TReturn> Partial<TC1, TC2, T1, T2, T3, T4, T5, TReturn>(this Func<TC1, TC2, T1, T2, T3, T4, T5, TReturn> function, TC1 tc1, TC2 tc2)
		{
			return (t1, t2, t3, t4, t5) => function(tc1, tc2, t1, t2, t3, t4, t5);
		}
		 
		public static Func<T1, T2, T3, T4, T5, TReturn> Partial<TC1, TC2, TC3, T1, T2, T3, T4, T5, TReturn>(this Func<TC1, TC2, TC3, T1, T2, T3, T4, T5, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3)
		{
			return (t1, t2, t3, t4, t5) => function(tc1, tc2, tc3, t1, t2, t3, t4, t5);
		}
		 
		public static Func<T1, T2, T3, T4, T5, TReturn> Partial<TC1, TC2, TC3, TC4, T1, T2, T3, T4, T5, TReturn>(this Func<TC1, TC2, TC3, TC4, T1, T2, T3, T4, T5, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4)
		{
			return (t1, t2, t3, t4, t5) => function(tc1, tc2, tc3, tc4, t1, t2, t3, t4, t5);
		}
		 
		public static Func<T1, T2, T3, T4, T5, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, T4, T5, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, T4, T5, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5)
		{
			return (t1, t2, t3, t4, t5) => function(tc1, tc2, tc3, tc4, tc5, t1, t2, t3, t4, t5);
		}
		 
		public static Func<T1, T2, T3, T4, T5, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, T3, T4, T5, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, T3, T4, T5, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6)
		{
			return (t1, t2, t3, t4, t5) => function(tc1, tc2, tc3, tc4, tc5, tc6, t1, t2, t3, t4, t5);
		}
		 
		public static Func<T1, T2, T3, T4, T5, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, T2, T3, T4, T5, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, T2, T3, T4, T5, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7)
		{
			return (t1, t2, t3, t4, t5) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, t1, t2, t3, t4, t5);
		}
		 
		public static Func<T1, T2, T3, T4, T5, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, T1, T2, T3, T4, T5, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, T1, T2, T3, T4, T5, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8)
		{
			return (t1, t2, t3, t4, t5) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, t1, t2, t3, t4, t5);
		}
		 
		public static Func<T1, T2, T3, T4, T5, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, T1, T2, T3, T4, T5, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, T1, T2, T3, T4, T5, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9)
		{
			return (t1, t2, t3, t4, t5) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, t1, t2, t3, t4, t5);
		}
		 
		public static Func<T1, T2, T3, T4, T5, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, T1, T2, T3, T4, T5, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, T1, T2, T3, T4, T5, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10)
		{
			return (t1, t2, t3, t4, t5) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, t1, t2, t3, t4, t5);
		}
		 
		public static Func<T1, T2, T3, T4, T5, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, T1, T2, T3, T4, T5, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, T1, T2, T3, T4, T5, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11)
		{
			return (t1, t2, t3, t4, t5) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, t1, t2, t3, t4, t5);
		}
		 
		public static Func<T1, T2, T3, T4, T5, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, T1, T2, T3, T4, T5, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, T1, T2, T3, T4, T5, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12)
		{
			return (t1, t2, t3, t4, t5) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, t1, t2, t3, t4, t5);
		}
		 
		public static Func<T1, T2, T3, T4, T5, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, T1, T2, T3, T4, T5, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, T1, T2, T3, T4, T5, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12, TC13 tc13)
		{
			return (t1, t2, t3, t4, t5) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, tc13, t1, t2, t3, t4, t5);
		}
		 
		public static Func<T1, T2, T3, T4, T5, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, T1, T2, T3, T4, T5, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, TC14, T1, T2, T3, T4, T5, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12, TC13 tc13, TC14 tc14)
		{
			return (t1, t2, t3, t4, t5) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, tc13, tc14, t1, t2, t3, t4, t5);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, TReturn> Partial<TC1, T1, T2, T3, T4, T5, T6, TReturn>(this Func<TC1, T1, T2, T3, T4, T5, T6, TReturn> function, TC1 tc1)
		{
			return (t1, t2, t3, t4, t5, t6) => function(tc1, t1, t2, t3, t4, t5, t6);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, TReturn> Partial<TC1, TC2, T1, T2, T3, T4, T5, T6, TReturn>(this Func<TC1, TC2, T1, T2, T3, T4, T5, T6, TReturn> function, TC1 tc1, TC2 tc2)
		{
			return (t1, t2, t3, t4, t5, t6) => function(tc1, tc2, t1, t2, t3, t4, t5, t6);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, TReturn> Partial<TC1, TC2, TC3, T1, T2, T3, T4, T5, T6, TReturn>(this Func<TC1, TC2, TC3, T1, T2, T3, T4, T5, T6, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3)
		{
			return (t1, t2, t3, t4, t5, t6) => function(tc1, tc2, tc3, t1, t2, t3, t4, t5, t6);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, TReturn> Partial<TC1, TC2, TC3, TC4, T1, T2, T3, T4, T5, T6, TReturn>(this Func<TC1, TC2, TC3, TC4, T1, T2, T3, T4, T5, T6, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4)
		{
			return (t1, t2, t3, t4, t5, t6) => function(tc1, tc2, tc3, tc4, t1, t2, t3, t4, t5, t6);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, T4, T5, T6, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, T4, T5, T6, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5)
		{
			return (t1, t2, t3, t4, t5, t6) => function(tc1, tc2, tc3, tc4, tc5, t1, t2, t3, t4, t5, t6);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, T3, T4, T5, T6, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, T3, T4, T5, T6, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6)
		{
			return (t1, t2, t3, t4, t5, t6) => function(tc1, tc2, tc3, tc4, tc5, tc6, t1, t2, t3, t4, t5, t6);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, T2, T3, T4, T5, T6, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, T2, T3, T4, T5, T6, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7)
		{
			return (t1, t2, t3, t4, t5, t6) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, t1, t2, t3, t4, t5, t6);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, T1, T2, T3, T4, T5, T6, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, T1, T2, T3, T4, T5, T6, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8)
		{
			return (t1, t2, t3, t4, t5, t6) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, t1, t2, t3, t4, t5, t6);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, T1, T2, T3, T4, T5, T6, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, T1, T2, T3, T4, T5, T6, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9)
		{
			return (t1, t2, t3, t4, t5, t6) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, t1, t2, t3, t4, t5, t6);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, T1, T2, T3, T4, T5, T6, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, T1, T2, T3, T4, T5, T6, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10)
		{
			return (t1, t2, t3, t4, t5, t6) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, t1, t2, t3, t4, t5, t6);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, T1, T2, T3, T4, T5, T6, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, T1, T2, T3, T4, T5, T6, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11)
		{
			return (t1, t2, t3, t4, t5, t6) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, t1, t2, t3, t4, t5, t6);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, T1, T2, T3, T4, T5, T6, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, T1, T2, T3, T4, T5, T6, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12)
		{
			return (t1, t2, t3, t4, t5, t6) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, t1, t2, t3, t4, t5, t6);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, T1, T2, T3, T4, T5, T6, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, TC13, T1, T2, T3, T4, T5, T6, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12, TC13 tc13)
		{
			return (t1, t2, t3, t4, t5, t6) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, tc13, t1, t2, t3, t4, t5, t6);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, TReturn> Partial<TC1, T1, T2, T3, T4, T5, T6, T7, TReturn>(this Func<TC1, T1, T2, T3, T4, T5, T6, T7, TReturn> function, TC1 tc1)
		{
			return (t1, t2, t3, t4, t5, t6, t7) => function(tc1, t1, t2, t3, t4, t5, t6, t7);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, TReturn> Partial<TC1, TC2, T1, T2, T3, T4, T5, T6, T7, TReturn>(this Func<TC1, TC2, T1, T2, T3, T4, T5, T6, T7, TReturn> function, TC1 tc1, TC2 tc2)
		{
			return (t1, t2, t3, t4, t5, t6, t7) => function(tc1, tc2, t1, t2, t3, t4, t5, t6, t7);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, TReturn> Partial<TC1, TC2, TC3, T1, T2, T3, T4, T5, T6, T7, TReturn>(this Func<TC1, TC2, TC3, T1, T2, T3, T4, T5, T6, T7, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3)
		{
			return (t1, t2, t3, t4, t5, t6, t7) => function(tc1, tc2, tc3, t1, t2, t3, t4, t5, t6, t7);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, TReturn> Partial<TC1, TC2, TC3, TC4, T1, T2, T3, T4, T5, T6, T7, TReturn>(this Func<TC1, TC2, TC3, TC4, T1, T2, T3, T4, T5, T6, T7, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4)
		{
			return (t1, t2, t3, t4, t5, t6, t7) => function(tc1, tc2, tc3, tc4, t1, t2, t3, t4, t5, t6, t7);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, T4, T5, T6, T7, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, T4, T5, T6, T7, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5)
		{
			return (t1, t2, t3, t4, t5, t6, t7) => function(tc1, tc2, tc3, tc4, tc5, t1, t2, t3, t4, t5, t6, t7);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, T3, T4, T5, T6, T7, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, T3, T4, T5, T6, T7, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6)
		{
			return (t1, t2, t3, t4, t5, t6, t7) => function(tc1, tc2, tc3, tc4, tc5, tc6, t1, t2, t3, t4, t5, t6, t7);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, T2, T3, T4, T5, T6, T7, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, T2, T3, T4, T5, T6, T7, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7)
		{
			return (t1, t2, t3, t4, t5, t6, t7) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, t1, t2, t3, t4, t5, t6, t7);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, T1, T2, T3, T4, T5, T6, T7, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, T1, T2, T3, T4, T5, T6, T7, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8)
		{
			return (t1, t2, t3, t4, t5, t6, t7) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, t1, t2, t3, t4, t5, t6, t7);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, T1, T2, T3, T4, T5, T6, T7, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, T1, T2, T3, T4, T5, T6, T7, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9)
		{
			return (t1, t2, t3, t4, t5, t6, t7) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, t1, t2, t3, t4, t5, t6, t7);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, T1, T2, T3, T4, T5, T6, T7, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, T1, T2, T3, T4, T5, T6, T7, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10)
		{
			return (t1, t2, t3, t4, t5, t6, t7) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, t1, t2, t3, t4, t5, t6, t7);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, T1, T2, T3, T4, T5, T6, T7, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, T1, T2, T3, T4, T5, T6, T7, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11)
		{
			return (t1, t2, t3, t4, t5, t6, t7) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, t1, t2, t3, t4, t5, t6, t7);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, T1, T2, T3, T4, T5, T6, T7, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, TC12, T1, T2, T3, T4, T5, T6, T7, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11, TC12 tc12)
		{
			return (t1, t2, t3, t4, t5, t6, t7) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, tc12, t1, t2, t3, t4, t5, t6, t7);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, TReturn> Partial<TC1, T1, T2, T3, T4, T5, T6, T7, T8, TReturn>(this Func<TC1, T1, T2, T3, T4, T5, T6, T7, T8, TReturn> function, TC1 tc1)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8) => function(tc1, t1, t2, t3, t4, t5, t6, t7, t8);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, TReturn> Partial<TC1, TC2, T1, T2, T3, T4, T5, T6, T7, T8, TReturn>(this Func<TC1, TC2, T1, T2, T3, T4, T5, T6, T7, T8, TReturn> function, TC1 tc1, TC2 tc2)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8) => function(tc1, tc2, t1, t2, t3, t4, t5, t6, t7, t8);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, TReturn> Partial<TC1, TC2, TC3, T1, T2, T3, T4, T5, T6, T7, T8, TReturn>(this Func<TC1, TC2, TC3, T1, T2, T3, T4, T5, T6, T7, T8, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8) => function(tc1, tc2, tc3, t1, t2, t3, t4, t5, t6, t7, t8);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, TReturn> Partial<TC1, TC2, TC3, TC4, T1, T2, T3, T4, T5, T6, T7, T8, TReturn>(this Func<TC1, TC2, TC3, TC4, T1, T2, T3, T4, T5, T6, T7, T8, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8) => function(tc1, tc2, tc3, tc4, t1, t2, t3, t4, t5, t6, t7, t8);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, T4, T5, T6, T7, T8, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, T4, T5, T6, T7, T8, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8) => function(tc1, tc2, tc3, tc4, tc5, t1, t2, t3, t4, t5, t6, t7, t8);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, T3, T4, T5, T6, T7, T8, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, T3, T4, T5, T6, T7, T8, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8) => function(tc1, tc2, tc3, tc4, tc5, tc6, t1, t2, t3, t4, t5, t6, t7, t8);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, T2, T3, T4, T5, T6, T7, T8, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, T2, T3, T4, T5, T6, T7, T8, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, t1, t2, t3, t4, t5, t6, t7, t8);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, T1, T2, T3, T4, T5, T6, T7, T8, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, T1, T2, T3, T4, T5, T6, T7, T8, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, t1, t2, t3, t4, t5, t6, t7, t8);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, T1, T2, T3, T4, T5, T6, T7, T8, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, T1, T2, T3, T4, T5, T6, T7, T8, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, t1, t2, t3, t4, t5, t6, t7, t8);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, T1, T2, T3, T4, T5, T6, T7, T8, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, T1, T2, T3, T4, T5, T6, T7, T8, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, t1, t2, t3, t4, t5, t6, t7, t8);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, T1, T2, T3, T4, T5, T6, T7, T8, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, TC11, T1, T2, T3, T4, T5, T6, T7, T8, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10, TC11 tc11)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, tc11, t1, t2, t3, t4, t5, t6, t7, t8);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn> Partial<TC1, T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn>(this Func<TC1, T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn> function, TC1 tc1)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9) => function(tc1, t1, t2, t3, t4, t5, t6, t7, t8, t9);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn> Partial<TC1, TC2, T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn>(this Func<TC1, TC2, T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn> function, TC1 tc1, TC2 tc2)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9) => function(tc1, tc2, t1, t2, t3, t4, t5, t6, t7, t8, t9);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn> Partial<TC1, TC2, TC3, T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn>(this Func<TC1, TC2, TC3, T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9) => function(tc1, tc2, tc3, t1, t2, t3, t4, t5, t6, t7, t8, t9);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn> Partial<TC1, TC2, TC3, TC4, T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn>(this Func<TC1, TC2, TC3, TC4, T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9) => function(tc1, tc2, tc3, tc4, t1, t2, t3, t4, t5, t6, t7, t8, t9);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9) => function(tc1, tc2, tc3, tc4, tc5, t1, t2, t3, t4, t5, t6, t7, t8, t9);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9) => function(tc1, tc2, tc3, tc4, tc5, tc6, t1, t2, t3, t4, t5, t6, t7, t8, t9);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, t1, t2, t3, t4, t5, t6, t7, t8, t9);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, t1, t2, t3, t4, t5, t6, t7, t8, t9);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, t1, t2, t3, t4, t5, t6, t7, t8, t9);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, TC10, T1, T2, T3, T4, T5, T6, T7, T8, T9, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9, TC10 tc10)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, tc10, t1, t2, t3, t4, t5, t6, t7, t8, t9);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn> Partial<TC1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn>(this Func<TC1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn> function, TC1 tc1)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10) => function(tc1, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn> Partial<TC1, TC2, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn>(this Func<TC1, TC2, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn> function, TC1 tc1, TC2 tc2)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10) => function(tc1, tc2, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn> Partial<TC1, TC2, TC3, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn>(this Func<TC1, TC2, TC3, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10) => function(tc1, tc2, tc3, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn> Partial<TC1, TC2, TC3, TC4, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn>(this Func<TC1, TC2, TC3, TC4, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10) => function(tc1, tc2, tc3, tc4, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10) => function(tc1, tc2, tc3, tc4, tc5, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10) => function(tc1, tc2, tc3, tc4, tc5, tc6, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, TC9, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8, TC9 tc9)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, tc9, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn> Partial<TC1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn>(this Func<TC1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn> function, TC1 tc1)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11) => function(tc1, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn> Partial<TC1, TC2, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn>(this Func<TC1, TC2, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn> function, TC1 tc1, TC2 tc2)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11) => function(tc1, tc2, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn> Partial<TC1, TC2, TC3, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn>(this Func<TC1, TC2, TC3, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11) => function(tc1, tc2, tc3, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn> Partial<TC1, TC2, TC3, TC4, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn>(this Func<TC1, TC2, TC3, TC4, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11) => function(tc1, tc2, tc3, tc4, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11) => function(tc1, tc2, tc3, tc4, tc5, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11) => function(tc1, tc2, tc3, tc4, tc5, tc6, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, TC8, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7, TC8 tc8)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, tc8, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn> Partial<TC1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn>(this Func<TC1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn> function, TC1 tc1)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12) => function(tc1, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn> Partial<TC1, TC2, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn>(this Func<TC1, TC2, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn> function, TC1 tc1, TC2 tc2)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12) => function(tc1, tc2, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn> Partial<TC1, TC2, TC3, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn>(this Func<TC1, TC2, TC3, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12) => function(tc1, tc2, tc3, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn> Partial<TC1, TC2, TC3, TC4, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn>(this Func<TC1, TC2, TC3, TC4, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12) => function(tc1, tc2, tc3, tc4, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12) => function(tc1, tc2, tc3, tc4, tc5, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12) => function(tc1, tc2, tc3, tc4, tc5, tc6, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, TC7, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6, TC7 tc7)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12) => function(tc1, tc2, tc3, tc4, tc5, tc6, tc7, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TReturn> Partial<TC1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TReturn>(this Func<TC1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TReturn> function, TC1 tc1)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13) => function(tc1, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TReturn> Partial<TC1, TC2, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TReturn>(this Func<TC1, TC2, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TReturn> function, TC1 tc1, TC2 tc2)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13) => function(tc1, tc2, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TReturn> Partial<TC1, TC2, TC3, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TReturn>(this Func<TC1, TC2, TC3, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13) => function(tc1, tc2, tc3, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TReturn> Partial<TC1, TC2, TC3, TC4, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TReturn>(this Func<TC1, TC2, TC3, TC4, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13) => function(tc1, tc2, tc3, tc4, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13) => function(tc1, tc2, tc3, tc4, tc5, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, TC6, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5, TC6 tc6)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13) => function(tc1, tc2, tc3, tc4, tc5, tc6, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TReturn> Partial<TC1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TReturn>(this Func<TC1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TReturn> function, TC1 tc1)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14) => function(tc1, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TReturn> Partial<TC1, TC2, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TReturn>(this Func<TC1, TC2, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TReturn> function, TC1 tc1, TC2 tc2)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14) => function(tc1, tc2, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TReturn> Partial<TC1, TC2, TC3, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TReturn>(this Func<TC1, TC2, TC3, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14) => function(tc1, tc2, tc3, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TReturn> Partial<TC1, TC2, TC3, TC4, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TReturn>(this Func<TC1, TC2, TC3, TC4, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14) => function(tc1, tc2, tc3, tc4, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TReturn> Partial<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TReturn>(this Func<TC1, TC2, TC3, TC4, TC5, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4, TC5 tc5)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14) => function(tc1, tc2, tc3, tc4, tc5, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TReturn> Partial<TC1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TReturn>(this Func<TC1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TReturn> function, TC1 tc1)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15) => function(tc1, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TReturn> Partial<TC1, TC2, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TReturn>(this Func<TC1, TC2, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TReturn> function, TC1 tc1, TC2 tc2)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15) => function(tc1, tc2, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TReturn> Partial<TC1, TC2, TC3, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TReturn>(this Func<TC1, TC2, TC3, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15) => function(tc1, tc2, tc3, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TReturn> Partial<TC1, TC2, TC3, TC4, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TReturn>(this Func<TC1, TC2, TC3, TC4, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3, TC4 tc4)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15) => function(tc1, tc2, tc3, tc4, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TReturn> Partial<TC1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TReturn>(this Func<TC1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TReturn> function, TC1 tc1)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16) => function(tc1, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TReturn> Partial<TC1, TC2, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TReturn>(this Func<TC1, TC2, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TReturn> function, TC1 tc1, TC2 tc2)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16) => function(tc1, tc2, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TReturn> Partial<TC1, TC2, TC3, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TReturn>(this Func<TC1, TC2, TC3, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TReturn> function, TC1 tc1, TC2 tc2, TC3 tc3)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16) => function(tc1, tc2, tc3, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, TReturn> Partial<TC1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, TReturn>(this Func<TC1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, TReturn> function, TC1 tc1)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17) => function(tc1, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, TReturn> Partial<TC1, TC2, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, TReturn>(this Func<TC1, TC2, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, TReturn> function, TC1 tc1, TC2 tc2)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17) => function(tc1, tc2, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17);
		}
		 
		public static Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, TReturn> Partial<TC1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, TReturn>(this Func<TC1, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, TReturn> function, TC1 tc1)
		{
			return (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18) => function(tc1, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18);
		}
		
	}
}

namespace System
{
	public delegate TResult Func<T1, T2, T3, T4, T5, TResult>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5);
	public delegate TResult Func<T1, T2, T3, T4, T5, T6, TResult>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6);
	public delegate TResult Func<T1, T2, T3, T4, T5, T6, T7, TResult>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7);
	public delegate TResult Func<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8);
	public delegate TResult Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, TResult>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9);
	public delegate TResult Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TResult>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10);
	public delegate TResult Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TResult>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11);
	public delegate TResult Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TResult>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12);
	public delegate TResult Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TResult>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13);
	public delegate TResult Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TResult>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13, T14 t14);
	public delegate TResult Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TResult>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13, T14 t14, T15 t15);
	public delegate TResult Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TResult>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13, T14 t14, T15 t15, T16 t16);
	public delegate TResult Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, TResult>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13, T14 t14, T15 t15, T16 t16, T17 t17);
	public delegate TResult Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, TResult>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13, T14 t14, T15 t15, T16 t16, T17 t17, T18 t18);
	public delegate TResult Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, TResult>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13, T14 t14, T15 t15, T16 t16, T17 t17, T18 t18, T19 t19);
	public delegate TResult Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, TResult>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13, T14 t14, T15 t15, T16 t16, T17 t17, T18 t18, T19 t19, T20 t20);
	
	public delegate void Action<T1, T2, T3, T4, T5>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5);
	public delegate void Action<T1, T2, T3, T4, T5, T6>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6);
	public delegate void Action<T1, T2, T3, T4, T5, T6, T7>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7);
	public delegate void Action<T1, T2, T3, T4, T5, T6, T7, T8>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8);
	public delegate void Action<T1, T2, T3, T4, T5, T6, T7, T8, T9>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9);
	public delegate void Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10);
	public delegate void Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11);
	public delegate void Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12);
	public delegate void Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13);
	public delegate void Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13, T14 t14);
	public delegate void Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13, T14 t14, T15 t15);
	public delegate void Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13, T14 t14, T15 t15, T16 t16);
	public delegate void Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13, T14 t14, T15 t15, T16 t16, T17 t17);
	public delegate void Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13, T14 t14, T15 t15, T16 t16, T17 t17, T18 t18);
	public delegate void Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13, T14 t14, T15 t15, T16 t16, T17 t17, T18 t18, T19 t19);
	public delegate void Action<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20>(T1 t1, T2 t2, T3 t3, T4 t4, T5 t5, T6 t6, T7 t7, T8 t8, T9 t9, T10 t10, T11 t11, T12 t12, T13 t13, T14 t14, T15 t15, T16 t16, T17 t17, T18 t18, T19 t19, T20 t20);
	}

