#region Copyright Kayomani 2010.  Licensed under the GPLv3 (Or later version), Expand for details. Do not remove this notice.
/**
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or any 
    later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * */
#endregion
// <auto-generated>
// This code was generated by a tool.
// LinqToWmi.ClassGenerator Version: 1.0.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if  the code is regenerated.
// </auto-generated>
namespace Fap.Foundation.WMI_Prototypes
{
    using System;
    using System.Linq;
    using LinqToWmi.Core.WMI;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("LinqToWmi.ClassGenerator", "1.0.0.0")]
    public class Win32_BIOS
    {

        private ushort[] _biosCharacteristics;

        private string[] _bIOSVersion;

        private string _buildNumber;

        private string _caption;

        private string _codeSet;

        private string _currentLanguage;

        private string _description;

        private string _identificationCode;

        private ushort _installableLanguages;

        private System.DateTime _installDate;

        private string _languageEdition;

        private string[] _listOfLanguages;

        private string _manufacturer;

        private string _name;

        private string _otherTargetOS;

        private bool _primaryBIOS;

        private System.DateTime _releaseDate;

        private string _serialNumber;

        private string _sMBIOSBIOSVersion;

        private ushort _sMBIOSMajorVersion;

        private ushort _sMBIOSMinorVersion;

        private bool _sMBIOSPresent;

        private string _softwareElementID;

        private ushort _softwareElementState;

        private string _status;

        private ushort _targetOperatingSystem;

        private string _version;

        /// <summary>
        /// Represents the property BiosCharacteristics
        /// </summary>
        public virtual ushort[] BiosCharacteristics
        {
            get
            {
                return this._biosCharacteristics;
            }
            set
            {
                this._biosCharacteristics = value;
            }
        }

        /// <summary>
        /// Represents the property BIOSVersion
        /// </summary>
        public virtual string[] BIOSVersion
        {
            get
            {
                return this._bIOSVersion;
            }
            set
            {
                this._bIOSVersion = value;
            }
        }

        /// <summary>
        /// Represents the property BuildNumber
        /// </summary>
        public virtual string BuildNumber
        {
            get
            {
                return this._buildNumber;
            }
            set
            {
                this._buildNumber = value;
            }
        }

        /// <summary>
        /// Represents the property Caption
        /// </summary>
        public virtual string Caption
        {
            get
            {
                return this._caption;
            }
            set
            {
                this._caption = value;
            }
        }

        /// <summary>
        /// Represents the property CodeSet
        /// </summary>
        public virtual string CodeSet
        {
            get
            {
                return this._codeSet;
            }
            set
            {
                this._codeSet = value;
            }
        }

        /// <summary>
        /// Represents the property CurrentLanguage
        /// </summary>
        public virtual string CurrentLanguage
        {
            get
            {
                return this._currentLanguage;
            }
            set
            {
                this._currentLanguage = value;
            }
        }

        /// <summary>
        /// Represents the property Description
        /// </summary>
        public virtual string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                this._description = value;
            }
        }

        /// <summary>
        /// Represents the property IdentificationCode
        /// </summary>
        public virtual string IdentificationCode
        {
            get
            {
                return this._identificationCode;
            }
            set
            {
                this._identificationCode = value;
            }
        }

        /// <summary>
        /// Represents the property InstallableLanguages
        /// </summary>
        public virtual ushort InstallableLanguages
        {
            get
            {
                return this._installableLanguages;
            }
            set
            {
                this._installableLanguages = value;
            }
        }

        /// <summary>
        /// Represents the property InstallDate
        /// </summary>
        public virtual System.DateTime InstallDate
        {
            get
            {
                return this._installDate;
            }
            set
            {
                this._installDate = value;
            }
        }

        /// <summary>
        /// Represents the property LanguageEdition
        /// </summary>
        public virtual string LanguageEdition
        {
            get
            {
                return this._languageEdition;
            }
            set
            {
                this._languageEdition = value;
            }
        }

        /// <summary>
        /// Represents the property ListOfLanguages
        /// </summary>
        public virtual string[] ListOfLanguages
        {
            get
            {
                return this._listOfLanguages;
            }
            set
            {
                this._listOfLanguages = value;
            }
        }

        /// <summary>
        /// Represents the property Manufacturer
        /// </summary>
        public virtual string Manufacturer
        {
            get
            {
                return this._manufacturer;
            }
            set
            {
                this._manufacturer = value;
            }
        }

        /// <summary>
        /// Represents the property Name
        /// </summary>
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }

        /// <summary>
        /// Represents the property OtherTargetOS
        /// </summary>
        public virtual string OtherTargetOS
        {
            get
            {
                return this._otherTargetOS;
            }
            set
            {
                this._otherTargetOS = value;
            }
        }

        /// <summary>
        /// Represents the property PrimaryBIOS
        /// </summary>
        public virtual bool PrimaryBIOS
        {
            get
            {
                return this._primaryBIOS;
            }
            set
            {
                this._primaryBIOS = value;
            }
        }

        /// <summary>
        /// Represents the property ReleaseDate
        /// </summary>
        public virtual System.DateTime ReleaseDate
        {
            get
            {
                return this._releaseDate;
            }
            set
            {
                this._releaseDate = value;
            }
        }

        /// <summary>
        /// Represents the property SerialNumber
        /// </summary>
        public virtual string SerialNumber
        {
            get
            {
                return this._serialNumber;
            }
            set
            {
                this._serialNumber = value;
            }
        }

        /// <summary>
        /// Represents the property SMBIOSBIOSVersion
        /// </summary>
        public virtual string SMBIOSBIOSVersion
        {
            get
            {
                return this._sMBIOSBIOSVersion;
            }
            set
            {
                this._sMBIOSBIOSVersion = value;
            }
        }

        /// <summary>
        /// Represents the property SMBIOSMajorVersion
        /// </summary>
        public virtual ushort SMBIOSMajorVersion
        {
            get
            {
                return this._sMBIOSMajorVersion;
            }
            set
            {
                this._sMBIOSMajorVersion = value;
            }
        }

        /// <summary>
        /// Represents the property SMBIOSMinorVersion
        /// </summary>
        public virtual ushort SMBIOSMinorVersion
        {
            get
            {
                return this._sMBIOSMinorVersion;
            }
            set
            {
                this._sMBIOSMinorVersion = value;
            }
        }

        /// <summary>
        /// Represents the property SMBIOSPresent
        /// </summary>
        public virtual bool SMBIOSPresent
        {
            get
            {
                return this._sMBIOSPresent;
            }
            set
            {
                this._sMBIOSPresent = value;
            }
        }

        /// <summary>
        /// Represents the property SoftwareElementID
        /// </summary>
        public virtual string SoftwareElementID
        {
            get
            {
                return this._softwareElementID;
            }
            set
            {
                this._softwareElementID = value;
            }
        }

        /// <summary>
        /// Represents the property SoftwareElementState
        /// </summary>
        public virtual ushort SoftwareElementState
        {
            get
            {
                return this._softwareElementState;
            }
            set
            {
                this._softwareElementState = value;
            }
        }

        /// <summary>
        /// Represents the property Status
        /// </summary>
        public virtual string Status
        {
            get
            {
                return this._status;
            }
            set
            {
                this._status = value;
            }
        }

        /// <summary>
        /// Represents the property TargetOperatingSystem
        /// </summary>
        public virtual ushort TargetOperatingSystem
        {
            get
            {
                return this._targetOperatingSystem;
            }
            set
            {
                this._targetOperatingSystem = value;
            }
        }

        /// <summary>
        /// Represents the property Version
        /// </summary>
        public virtual string Version
        {
            get
            {
                return this._version;
            }
            set
            {
                this._version = value;
            }
        }
    }
}
