#region Copyright Kayomani 2010.  Licensed under the GPLv3 (Or later version), Expand for details. Do not remove this notice.
/**
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or any 
    later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * */
#endregion
// <auto-generated>
// This code was generated by a tool.
// LinqToWmi.ClassGenerator Version: 1.0.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if  the code is regenerated.
// </auto-generated>
namespace Fap.Foundation.WMI_Prototypes
{
    using System;
    using System.Linq;
    using LinqToWmi.Core.WMI;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("LinqToWmi.ClassGenerator", "1.0.0.0")]
    public class Win32_PhysicalMemory
    {

        private string _bankLabel;

        private ulong _capacity;

        private string _caption;

        private string _creationClassName;

        private ushort _dataWidth;

        private string _description;

        private string _deviceLocator;

        private ushort _formFactor;

        private bool _hotSwappable;

        private System.DateTime _installDate;

        private ushort _interleaveDataDepth;

        private uint _interleavePosition;

        private string _manufacturer;

        private ushort _memoryType;

        private string _model;

        private string _name;

        private string _otherIdentifyingInfo;

        private string _partNumber;

        private uint _positionInRow;

        private bool _poweredOn;

        private bool _removable;

        private bool _replaceable;

        private string _serialNumber;

        private string _sKU;

        private uint _speed;

        private string _status;

        private string _tag;

        private ushort _totalWidth;

        private ushort _typeDetail;

        private string _version;

        /// <summary>
        /// Represents the property BankLabel
        /// </summary>
        public virtual string BankLabel
        {
            get
            {
                return this._bankLabel;
            }
            set
            {
                this._bankLabel = value;
            }
        }

        /// <summary>
        /// Represents the property Capacity
        /// </summary>
        public virtual ulong Capacity
        {
            get
            {
                return this._capacity;
            }
            set
            {
                this._capacity = value;
            }
        }

        /// <summary>
        /// Represents the property Caption
        /// </summary>
        public virtual string Caption
        {
            get
            {
                return this._caption;
            }
            set
            {
                this._caption = value;
            }
        }

        /// <summary>
        /// Represents the property CreationClassName
        /// </summary>
        public virtual string CreationClassName
        {
            get
            {
                return this._creationClassName;
            }
            set
            {
                this._creationClassName = value;
            }
        }

        /// <summary>
        /// Represents the property DataWidth
        /// </summary>
        public virtual ushort DataWidth
        {
            get
            {
                return this._dataWidth;
            }
            set
            {
                this._dataWidth = value;
            }
        }

        /// <summary>
        /// Represents the property Description
        /// </summary>
        public virtual string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                this._description = value;
            }
        }

        /// <summary>
        /// Represents the property DeviceLocator
        /// </summary>
        public virtual string DeviceLocator
        {
            get
            {
                return this._deviceLocator;
            }
            set
            {
                this._deviceLocator = value;
            }
        }

        /// <summary>
        /// Represents the property FormFactor
        /// </summary>
        public virtual ushort FormFactor
        {
            get
            {
                return this._formFactor;
            }
            set
            {
                this._formFactor = value;
            }
        }

        /// <summary>
        /// Represents the property HotSwappable
        /// </summary>
        public virtual bool HotSwappable
        {
            get
            {
                return this._hotSwappable;
            }
            set
            {
                this._hotSwappable = value;
            }
        }

        /// <summary>
        /// Represents the property InstallDate
        /// </summary>
        public virtual System.DateTime InstallDate
        {
            get
            {
                return this._installDate;
            }
            set
            {
                this._installDate = value;
            }
        }

        /// <summary>
        /// Represents the property InterleaveDataDepth
        /// </summary>
        public virtual ushort InterleaveDataDepth
        {
            get
            {
                return this._interleaveDataDepth;
            }
            set
            {
                this._interleaveDataDepth = value;
            }
        }

        /// <summary>
        /// Represents the property InterleavePosition
        /// </summary>
        public virtual uint InterleavePosition
        {
            get
            {
                return this._interleavePosition;
            }
            set
            {
                this._interleavePosition = value;
            }
        }

        /// <summary>
        /// Represents the property Manufacturer
        /// </summary>
        public virtual string Manufacturer
        {
            get
            {
                return this._manufacturer;
            }
            set
            {
                this._manufacturer = value;
            }
        }

        /// <summary>
        /// Represents the property MemoryType
        /// </summary>
        public virtual ushort MemoryType
        {
            get
            {
                return this._memoryType;
            }
            set
            {
                this._memoryType = value;
            }
        }

        /// <summary>
        /// Represents the property Model
        /// </summary>
        public virtual string Model
        {
            get
            {
                return this._model;
            }
            set
            {
                this._model = value;
            }
        }

        /// <summary>
        /// Represents the property Name
        /// </summary>
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }

        /// <summary>
        /// Represents the property OtherIdentifyingInfo
        /// </summary>
        public virtual string OtherIdentifyingInfo
        {
            get
            {
                return this._otherIdentifyingInfo;
            }
            set
            {
                this._otherIdentifyingInfo = value;
            }
        }

        /// <summary>
        /// Represents the property PartNumber
        /// </summary>
        public virtual string PartNumber
        {
            get
            {
                return this._partNumber;
            }
            set
            {
                this._partNumber = value;
            }
        }

        /// <summary>
        /// Represents the property PositionInRow
        /// </summary>
        public virtual uint PositionInRow
        {
            get
            {
                return this._positionInRow;
            }
            set
            {
                this._positionInRow = value;
            }
        }

        /// <summary>
        /// Represents the property PoweredOn
        /// </summary>
        public virtual bool PoweredOn
        {
            get
            {
                return this._poweredOn;
            }
            set
            {
                this._poweredOn = value;
            }
        }

        /// <summary>
        /// Represents the property Removable
        /// </summary>
        public virtual bool Removable
        {
            get
            {
                return this._removable;
            }
            set
            {
                this._removable = value;
            }
        }

        /// <summary>
        /// Represents the property Replaceable
        /// </summary>
        public virtual bool Replaceable
        {
            get
            {
                return this._replaceable;
            }
            set
            {
                this._replaceable = value;
            }
        }

        /// <summary>
        /// Represents the property SerialNumber
        /// </summary>
        public virtual string SerialNumber
        {
            get
            {
                return this._serialNumber;
            }
            set
            {
                this._serialNumber = value;
            }
        }

        /// <summary>
        /// Represents the property SKU
        /// </summary>
        public virtual string SKU
        {
            get
            {
                return this._sKU;
            }
            set
            {
                this._sKU = value;
            }
        }

        /// <summary>
        /// Represents the property Speed
        /// </summary>
        public virtual uint Speed
        {
            get
            {
                return this._speed;
            }
            set
            {
                this._speed = value;
            }
        }

        /// <summary>
        /// Represents the property Status
        /// </summary>
        public virtual string Status
        {
            get
            {
                return this._status;
            }
            set
            {
                this._status = value;
            }
        }

        /// <summary>
        /// Represents the property Tag
        /// </summary>
        public virtual string Tag
        {
            get
            {
                return this._tag;
            }
            set
            {
                this._tag = value;
            }
        }

        /// <summary>
        /// Represents the property TotalWidth
        /// </summary>
        public virtual ushort TotalWidth
        {
            get
            {
                return this._totalWidth;
            }
            set
            {
                this._totalWidth = value;
            }
        }

        /// <summary>
        /// Represents the property TypeDetail
        /// </summary>
        public virtual ushort TypeDetail
        {
            get
            {
                return this._typeDetail;
            }
            set
            {
                this._typeDetail = value;
            }
        }

        /// <summary>
        /// Represents the property Version
        /// </summary>
        public virtual string Version
        {
            get
            {
                return this._version;
            }
            set
            {
                this._version = value;
            }
        }
    }
}