#region Copyright Kayomani 2010.  Licensed under the GPLv3 (Or later version), Expand for details. Do not remove this notice.
/**
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or any 
    later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * */
#endregion
// <auto-generated>
// This code was generated by a tool.
// LinqToWmi.ClassGenerator Version: 1.0.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if  the code is regenerated.
// </auto-generated>
namespace Fap.Foundation.WMI_Prototypes
{
    using System;
    using System.Linq;
    using LinqToWmi.Core.WMI;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("LinqToWmi.ClassGenerator", "1.0.0.0")]
    public class Win32_NetworkAdapter
    {

        private string _adapterType;

        private ushort _adapterTypeId;

        private bool _autoSense;

        private ushort _availability;

        private string _caption;

        private uint _configManagerErrorCode;

        private bool _configManagerUserConfig;

        private string _creationClassName;

        private string _description;

        private string _deviceID;

        private bool _errorCleared;

        private string _errorDescription;

        private string _gUID;

        private uint _index;

        private System.DateTime _installDate;

        private bool _installed;

        private uint _interfaceIndex;

        private uint _lastErrorCode;

        private string _mACAddress;

        private string _manufacturer;

        private uint _maxNumberControlled;

        private ulong _maxSpeed;

        private string _name;

        private string _netConnectionID;

        private ushort _netConnectionStatus;

        private bool _netEnabled;

        private string[] _networkAddresses;

        private string _permanentAddress;

        private bool _physicalAdapter;

        private string _pNPDeviceID;

        private ushort[] _powerManagementCapabilities;

        private bool _powerManagementSupported;

        private string _productName;

        private string _serviceName;

        private ulong _speed;

        private string _status;

        private ushort _statusInfo;

        private string _systemCreationClassName;

        private string _systemName;

        private System.DateTime _timeOfLastReset;

        /// <summary>
        /// Represents the property AdapterType
        /// </summary>
        public virtual string AdapterType
        {
            get
            {
                return this._adapterType;
            }
            set
            {
                this._adapterType = value;
            }
        }

        /// <summary>
        /// Represents the property AdapterTypeId
        /// </summary>
        public virtual ushort AdapterTypeId
        {
            get
            {
                return this._adapterTypeId;
            }
            set
            {
                this._adapterTypeId = value;
            }
        }

        /// <summary>
        /// Represents the property AutoSense
        /// </summary>
        public virtual bool AutoSense
        {
            get
            {
                return this._autoSense;
            }
            set
            {
                this._autoSense = value;
            }
        }

        /// <summary>
        /// Represents the property Availability
        /// </summary>
        public virtual ushort Availability
        {
            get
            {
                return this._availability;
            }
            set
            {
                this._availability = value;
            }
        }

        /// <summary>
        /// Represents the property Caption
        /// </summary>
        public virtual string Caption
        {
            get
            {
                return this._caption;
            }
            set
            {
                this._caption = value;
            }
        }

        /// <summary>
        /// Represents the property ConfigManagerErrorCode
        /// </summary>
        public virtual uint ConfigManagerErrorCode
        {
            get
            {
                return this._configManagerErrorCode;
            }
            set
            {
                this._configManagerErrorCode = value;
            }
        }

        /// <summary>
        /// Represents the property ConfigManagerUserConfig
        /// </summary>
        public virtual bool ConfigManagerUserConfig
        {
            get
            {
                return this._configManagerUserConfig;
            }
            set
            {
                this._configManagerUserConfig = value;
            }
        }

        /// <summary>
        /// Represents the property CreationClassName
        /// </summary>
        public virtual string CreationClassName
        {
            get
            {
                return this._creationClassName;
            }
            set
            {
                this._creationClassName = value;
            }
        }

        /// <summary>
        /// Represents the property Description
        /// </summary>
        public virtual string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                this._description = value;
            }
        }

        /// <summary>
        /// Represents the property DeviceID
        /// </summary>
        public virtual string DeviceID
        {
            get
            {
                return this._deviceID;
            }
            set
            {
                this._deviceID = value;
            }
        }

        /// <summary>
        /// Represents the property ErrorCleared
        /// </summary>
        public virtual bool ErrorCleared
        {
            get
            {
                return this._errorCleared;
            }
            set
            {
                this._errorCleared = value;
            }
        }

        /// <summary>
        /// Represents the property ErrorDescription
        /// </summary>
        public virtual string ErrorDescription
        {
            get
            {
                return this._errorDescription;
            }
            set
            {
                this._errorDescription = value;
            }
        }

        /// <summary>
        /// Represents the property GUID
        /// </summary>
        public virtual string GUID
        {
            get
            {
                return this._gUID;
            }
            set
            {
                this._gUID = value;
            }
        }

        /// <summary>
        /// Represents the property Index
        /// </summary>
        public virtual uint Index
        {
            get
            {
                return this._index;
            }
            set
            {
                this._index = value;
            }
        }

        /// <summary>
        /// Represents the property InstallDate
        /// </summary>
        public virtual System.DateTime InstallDate
        {
            get
            {
                return this._installDate;
            }
            set
            {
                this._installDate = value;
            }
        }

        /// <summary>
        /// Represents the property Installed
        /// </summary>
        public virtual bool Installed
        {
            get
            {
                return this._installed;
            }
            set
            {
                this._installed = value;
            }
        }

        /// <summary>
        /// Represents the property InterfaceIndex
        /// </summary>
        public virtual uint InterfaceIndex
        {
            get
            {
                return this._interfaceIndex;
            }
            set
            {
                this._interfaceIndex = value;
            }
        }

        /// <summary>
        /// Represents the property LastErrorCode
        /// </summary>
        public virtual uint LastErrorCode
        {
            get
            {
                return this._lastErrorCode;
            }
            set
            {
                this._lastErrorCode = value;
            }
        }

        /// <summary>
        /// Represents the property MACAddress
        /// </summary>
        public virtual string MACAddress
        {
            get
            {
                return this._mACAddress;
            }
            set
            {
                this._mACAddress = value;
            }
        }

        /// <summary>
        /// Represents the property Manufacturer
        /// </summary>
        public virtual string Manufacturer
        {
            get
            {
                return this._manufacturer;
            }
            set
            {
                this._manufacturer = value;
            }
        }

        /// <summary>
        /// Represents the property MaxNumberControlled
        /// </summary>
        public virtual uint MaxNumberControlled
        {
            get
            {
                return this._maxNumberControlled;
            }
            set
            {
                this._maxNumberControlled = value;
            }
        }

        /// <summary>
        /// Represents the property MaxSpeed
        /// </summary>
        public virtual ulong MaxSpeed
        {
            get
            {
                return this._maxSpeed;
            }
            set
            {
                this._maxSpeed = value;
            }
        }

        /// <summary>
        /// Represents the property Name
        /// </summary>
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }

        /// <summary>
        /// Represents the property NetConnectionID
        /// </summary>
        public virtual string NetConnectionID
        {
            get
            {
                return this._netConnectionID;
            }
            set
            {
                this._netConnectionID = value;
            }
        }

        /// <summary>
        /// Represents the property NetConnectionStatus
        /// </summary>
        public virtual ushort NetConnectionStatus
        {
            get
            {
                return this._netConnectionStatus;
            }
            set
            {
                this._netConnectionStatus = value;
            }
        }

        /// <summary>
        /// Represents the property NetEnabled
        /// </summary>
        public virtual bool NetEnabled
        {
            get
            {
                return this._netEnabled;
            }
            set
            {
                this._netEnabled = value;
            }
        }

        /// <summary>
        /// Represents the property NetworkAddresses
        /// </summary>
        public virtual string[] NetworkAddresses
        {
            get
            {
                return this._networkAddresses;
            }
            set
            {
                this._networkAddresses = value;
            }
        }

        /// <summary>
        /// Represents the property PermanentAddress
        /// </summary>
        public virtual string PermanentAddress
        {
            get
            {
                return this._permanentAddress;
            }
            set
            {
                this._permanentAddress = value;
            }
        }

        /// <summary>
        /// Represents the property PhysicalAdapter
        /// </summary>
        public virtual bool PhysicalAdapter
        {
            get
            {
                return this._physicalAdapter;
            }
            set
            {
                this._physicalAdapter = value;
            }
        }

        /// <summary>
        /// Represents the property PNPDeviceID
        /// </summary>
        public virtual string PNPDeviceID
        {
            get
            {
                return this._pNPDeviceID;
            }
            set
            {
                this._pNPDeviceID = value;
            }
        }

        /// <summary>
        /// Represents the property PowerManagementCapabilities
        /// </summary>
        public virtual ushort[] PowerManagementCapabilities
        {
            get
            {
                return this._powerManagementCapabilities;
            }
            set
            {
                this._powerManagementCapabilities = value;
            }
        }

        /// <summary>
        /// Represents the property PowerManagementSupported
        /// </summary>
        public virtual bool PowerManagementSupported
        {
            get
            {
                return this._powerManagementSupported;
            }
            set
            {
                this._powerManagementSupported = value;
            }
        }

        /// <summary>
        /// Represents the property ProductName
        /// </summary>
        public virtual string ProductName
        {
            get
            {
                return this._productName;
            }
            set
            {
                this._productName = value;
            }
        }

        /// <summary>
        /// Represents the property ServiceName
        /// </summary>
        public virtual string ServiceName
        {
            get
            {
                return this._serviceName;
            }
            set
            {
                this._serviceName = value;
            }
        }

        /// <summary>
        /// Represents the property Speed
        /// </summary>
        public virtual ulong Speed
        {
            get
            {
                return this._speed;
            }
            set
            {
                this._speed = value;
            }
        }

        /// <summary>
        /// Represents the property Status
        /// </summary>
        public virtual string Status
        {
            get
            {
                return this._status;
            }
            set
            {
                this._status = value;
            }
        }

        /// <summary>
        /// Represents the property StatusInfo
        /// </summary>
        public virtual ushort StatusInfo
        {
            get
            {
                return this._statusInfo;
            }
            set
            {
                this._statusInfo = value;
            }
        }

        /// <summary>
        /// Represents the property SystemCreationClassName
        /// </summary>
        public virtual string SystemCreationClassName
        {
            get
            {
                return this._systemCreationClassName;
            }
            set
            {
                this._systemCreationClassName = value;
            }
        }

        /// <summary>
        /// Represents the property SystemName
        /// </summary>
        public virtual string SystemName
        {
            get
            {
                return this._systemName;
            }
            set
            {
                this._systemName = value;
            }
        }

        /// <summary>
        /// Represents the property TimeOfLastReset
        /// </summary>
        public virtual System.DateTime TimeOfLastReset
        {
            get
            {
                return this._timeOfLastReset;
            }
            set
            {
                this._timeOfLastReset = value;
            }
        }
    }
}
