#region Copyright Kayomani 2010.  Licensed under the GPLv3 (Or later version), Expand for details. Do not remove this notice.
/**
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or any 
    later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * */
#endregion
// <auto-generated>
// This code was generated by a tool.
// LinqToWmi.ClassGenerator Version: 1.0.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if  the code is regenerated.
// </auto-generated>
namespace Fap.Foundation.WMI_Prototypes
{
    using System;
    using System.Linq;
    using LinqToWmi.Core.WMI;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("LinqToWmi.ClassGenerator", "1.0.0.0")]
    public class Win32_VideoController
    {

        private ushort[] _acceleratorCapabilities;

        private string _adapterCompatibility;

        private string _adapterDACType;

        private uint _adapterRAM;

        private ushort _availability;

        private string[] _capabilityDescriptions;

        private string _caption;

        private uint _colorTableEntries;

        private uint _configManagerErrorCode;

        private bool _configManagerUserConfig;

        private string _creationClassName;

        private uint _currentBitsPerPixel;

        private uint _currentHorizontalResolution;

        private ulong _currentNumberOfColors;

        private uint _currentNumberOfColumns;

        private uint _currentNumberOfRows;

        private uint _currentRefreshRate;

        private ushort _currentScanMode;

        private uint _currentVerticalResolution;

        private string _description;

        private string _deviceID;

        private uint _deviceSpecificPens;

        private uint _ditherType;

        private System.DateTime _driverDate;

        private string _driverVersion;

        private bool _errorCleared;

        private string _errorDescription;

        private uint _iCMIntent;

        private uint _iCMMethod;

        private string _infFilename;

        private string _infSection;

        private System.DateTime _installDate;

        private string _installedDisplayDrivers;

        private uint _lastErrorCode;

        private uint _maxMemorySupported;

        private uint _maxNumberControlled;

        private uint _maxRefreshRate;

        private uint _minRefreshRate;

        private bool _monochrome;

        private string _name;

        private ushort _numberOfColorPlanes;

        private uint _numberOfVideoPages;

        private string _pNPDeviceID;

        private ushort[] _powerManagementCapabilities;

        private bool _powerManagementSupported;

        private ushort _protocolSupported;

        private uint _reservedSystemPaletteEntries;

        private uint _specificationVersion;

        private string _status;

        private ushort _statusInfo;

        private string _systemCreationClassName;

        private string _systemName;

        private uint _systemPaletteEntries;

        private System.DateTime _timeOfLastReset;

        private ushort _videoArchitecture;

        private ushort _videoMemoryType;

        private ushort _videoMode;

        private string _videoModeDescription;

        private string _videoProcessor;

        /// <summary>
        /// Represents the property AcceleratorCapabilities
        /// </summary>
        public virtual ushort[] AcceleratorCapabilities
        {
            get
            {
                return this._acceleratorCapabilities;
            }
            set
            {
                this._acceleratorCapabilities = value;
            }
        }

        /// <summary>
        /// Represents the property AdapterCompatibility
        /// </summary>
        public virtual string AdapterCompatibility
        {
            get
            {
                return this._adapterCompatibility;
            }
            set
            {
                this._adapterCompatibility = value;
            }
        }

        /// <summary>
        /// Represents the property AdapterDACType
        /// </summary>
        public virtual string AdapterDACType
        {
            get
            {
                return this._adapterDACType;
            }
            set
            {
                this._adapterDACType = value;
            }
        }

        /// <summary>
        /// Represents the property AdapterRAM
        /// </summary>
        public virtual uint AdapterRAM
        {
            get
            {
                return this._adapterRAM;
            }
            set
            {
                this._adapterRAM = value;
            }
        }

        /// <summary>
        /// Represents the property Availability
        /// </summary>
        public virtual ushort Availability
        {
            get
            {
                return this._availability;
            }
            set
            {
                this._availability = value;
            }
        }

        /// <summary>
        /// Represents the property CapabilityDescriptions
        /// </summary>
        public virtual string[] CapabilityDescriptions
        {
            get
            {
                return this._capabilityDescriptions;
            }
            set
            {
                this._capabilityDescriptions = value;
            }
        }

        /// <summary>
        /// Represents the property Caption
        /// </summary>
        public virtual string Caption
        {
            get
            {
                return this._caption;
            }
            set
            {
                this._caption = value;
            }
        }

        /// <summary>
        /// Represents the property ColorTableEntries
        /// </summary>
        public virtual uint ColorTableEntries
        {
            get
            {
                return this._colorTableEntries;
            }
            set
            {
                this._colorTableEntries = value;
            }
        }

        /// <summary>
        /// Represents the property ConfigManagerErrorCode
        /// </summary>
        public virtual uint ConfigManagerErrorCode
        {
            get
            {
                return this._configManagerErrorCode;
            }
            set
            {
                this._configManagerErrorCode = value;
            }
        }

        /// <summary>
        /// Represents the property ConfigManagerUserConfig
        /// </summary>
        public virtual bool ConfigManagerUserConfig
        {
            get
            {
                return this._configManagerUserConfig;
            }
            set
            {
                this._configManagerUserConfig = value;
            }
        }

        /// <summary>
        /// Represents the property CreationClassName
        /// </summary>
        public virtual string CreationClassName
        {
            get
            {
                return this._creationClassName;
            }
            set
            {
                this._creationClassName = value;
            }
        }

        /// <summary>
        /// Represents the property CurrentBitsPerPixel
        /// </summary>
        public virtual uint CurrentBitsPerPixel
        {
            get
            {
                return this._currentBitsPerPixel;
            }
            set
            {
                this._currentBitsPerPixel = value;
            }
        }

        /// <summary>
        /// Represents the property CurrentHorizontalResolution
        /// </summary>
        public virtual uint CurrentHorizontalResolution
        {
            get
            {
                return this._currentHorizontalResolution;
            }
            set
            {
                this._currentHorizontalResolution = value;
            }
        }

        /// <summary>
        /// Represents the property CurrentNumberOfColors
        /// </summary>
        public virtual ulong CurrentNumberOfColors
        {
            get
            {
                return this._currentNumberOfColors;
            }
            set
            {
                this._currentNumberOfColors = value;
            }
        }

        /// <summary>
        /// Represents the property CurrentNumberOfColumns
        /// </summary>
        public virtual uint CurrentNumberOfColumns
        {
            get
            {
                return this._currentNumberOfColumns;
            }
            set
            {
                this._currentNumberOfColumns = value;
            }
        }

        /// <summary>
        /// Represents the property CurrentNumberOfRows
        /// </summary>
        public virtual uint CurrentNumberOfRows
        {
            get
            {
                return this._currentNumberOfRows;
            }
            set
            {
                this._currentNumberOfRows = value;
            }
        }

        /// <summary>
        /// Represents the property CurrentRefreshRate
        /// </summary>
        public virtual uint CurrentRefreshRate
        {
            get
            {
                return this._currentRefreshRate;
            }
            set
            {
                this._currentRefreshRate = value;
            }
        }

        /// <summary>
        /// Represents the property CurrentScanMode
        /// </summary>
        public virtual ushort CurrentScanMode
        {
            get
            {
                return this._currentScanMode;
            }
            set
            {
                this._currentScanMode = value;
            }
        }

        /// <summary>
        /// Represents the property CurrentVerticalResolution
        /// </summary>
        public virtual uint CurrentVerticalResolution
        {
            get
            {
                return this._currentVerticalResolution;
            }
            set
            {
                this._currentVerticalResolution = value;
            }
        }

        /// <summary>
        /// Represents the property Description
        /// </summary>
        public virtual string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                this._description = value;
            }
        }

        /// <summary>
        /// Represents the property DeviceID
        /// </summary>
        public virtual string DeviceID
        {
            get
            {
                return this._deviceID;
            }
            set
            {
                this._deviceID = value;
            }
        }

        /// <summary>
        /// Represents the property DeviceSpecificPens
        /// </summary>
        public virtual uint DeviceSpecificPens
        {
            get
            {
                return this._deviceSpecificPens;
            }
            set
            {
                this._deviceSpecificPens = value;
            }
        }

        /// <summary>
        /// Represents the property DitherType
        /// </summary>
        public virtual uint DitherType
        {
            get
            {
                return this._ditherType;
            }
            set
            {
                this._ditherType = value;
            }
        }

        /// <summary>
        /// Represents the property DriverDate
        /// </summary>
        public virtual System.DateTime DriverDate
        {
            get
            {
                return this._driverDate;
            }
            set
            {
                this._driverDate = value;
            }
        }

        /// <summary>
        /// Represents the property DriverVersion
        /// </summary>
        public virtual string DriverVersion
        {
            get
            {
                return this._driverVersion;
            }
            set
            {
                this._driverVersion = value;
            }
        }

        /// <summary>
        /// Represents the property ErrorCleared
        /// </summary>
        public virtual bool ErrorCleared
        {
            get
            {
                return this._errorCleared;
            }
            set
            {
                this._errorCleared = value;
            }
        }

        /// <summary>
        /// Represents the property ErrorDescription
        /// </summary>
        public virtual string ErrorDescription
        {
            get
            {
                return this._errorDescription;
            }
            set
            {
                this._errorDescription = value;
            }
        }

        /// <summary>
        /// Represents the property ICMIntent
        /// </summary>
        public virtual uint ICMIntent
        {
            get
            {
                return this._iCMIntent;
            }
            set
            {
                this._iCMIntent = value;
            }
        }

        /// <summary>
        /// Represents the property ICMMethod
        /// </summary>
        public virtual uint ICMMethod
        {
            get
            {
                return this._iCMMethod;
            }
            set
            {
                this._iCMMethod = value;
            }
        }

        /// <summary>
        /// Represents the property InfFilename
        /// </summary>
        public virtual string InfFilename
        {
            get
            {
                return this._infFilename;
            }
            set
            {
                this._infFilename = value;
            }
        }

        /// <summary>
        /// Represents the property InfSection
        /// </summary>
        public virtual string InfSection
        {
            get
            {
                return this._infSection;
            }
            set
            {
                this._infSection = value;
            }
        }

        /// <summary>
        /// Represents the property InstallDate
        /// </summary>
        public virtual System.DateTime InstallDate
        {
            get
            {
                return this._installDate;
            }
            set
            {
                this._installDate = value;
            }
        }

        /// <summary>
        /// Represents the property InstalledDisplayDrivers
        /// </summary>
        public virtual string InstalledDisplayDrivers
        {
            get
            {
                return this._installedDisplayDrivers;
            }
            set
            {
                this._installedDisplayDrivers = value;
            }
        }

        /// <summary>
        /// Represents the property LastErrorCode
        /// </summary>
        public virtual uint LastErrorCode
        {
            get
            {
                return this._lastErrorCode;
            }
            set
            {
                this._lastErrorCode = value;
            }
        }

        /// <summary>
        /// Represents the property MaxMemorySupported
        /// </summary>
        public virtual uint MaxMemorySupported
        {
            get
            {
                return this._maxMemorySupported;
            }
            set
            {
                this._maxMemorySupported = value;
            }
        }

        /// <summary>
        /// Represents the property MaxNumberControlled
        /// </summary>
        public virtual uint MaxNumberControlled
        {
            get
            {
                return this._maxNumberControlled;
            }
            set
            {
                this._maxNumberControlled = value;
            }
        }

        /// <summary>
        /// Represents the property MaxRefreshRate
        /// </summary>
        public virtual uint MaxRefreshRate
        {
            get
            {
                return this._maxRefreshRate;
            }
            set
            {
                this._maxRefreshRate = value;
            }
        }

        /// <summary>
        /// Represents the property MinRefreshRate
        /// </summary>
        public virtual uint MinRefreshRate
        {
            get
            {
                return this._minRefreshRate;
            }
            set
            {
                this._minRefreshRate = value;
            }
        }

        /// <summary>
        /// Represents the property Monochrome
        /// </summary>
        public virtual bool Monochrome
        {
            get
            {
                return this._monochrome;
            }
            set
            {
                this._monochrome = value;
            }
        }

        /// <summary>
        /// Represents the property Name
        /// </summary>
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }

        /// <summary>
        /// Represents the property NumberOfColorPlanes
        /// </summary>
        public virtual ushort NumberOfColorPlanes
        {
            get
            {
                return this._numberOfColorPlanes;
            }
            set
            {
                this._numberOfColorPlanes = value;
            }
        }

        /// <summary>
        /// Represents the property NumberOfVideoPages
        /// </summary>
        public virtual uint NumberOfVideoPages
        {
            get
            {
                return this._numberOfVideoPages;
            }
            set
            {
                this._numberOfVideoPages = value;
            }
        }

        /// <summary>
        /// Represents the property PNPDeviceID
        /// </summary>
        public virtual string PNPDeviceID
        {
            get
            {
                return this._pNPDeviceID;
            }
            set
            {
                this._pNPDeviceID = value;
            }
        }

        /// <summary>
        /// Represents the property PowerManagementCapabilities
        /// </summary>
        public virtual ushort[] PowerManagementCapabilities
        {
            get
            {
                return this._powerManagementCapabilities;
            }
            set
            {
                this._powerManagementCapabilities = value;
            }
        }

        /// <summary>
        /// Represents the property PowerManagementSupported
        /// </summary>
        public virtual bool PowerManagementSupported
        {
            get
            {
                return this._powerManagementSupported;
            }
            set
            {
                this._powerManagementSupported = value;
            }
        }

        /// <summary>
        /// Represents the property ProtocolSupported
        /// </summary>
        public virtual ushort ProtocolSupported
        {
            get
            {
                return this._protocolSupported;
            }
            set
            {
                this._protocolSupported = value;
            }
        }

        /// <summary>
        /// Represents the property ReservedSystemPaletteEntries
        /// </summary>
        public virtual uint ReservedSystemPaletteEntries
        {
            get
            {
                return this._reservedSystemPaletteEntries;
            }
            set
            {
                this._reservedSystemPaletteEntries = value;
            }
        }

        /// <summary>
        /// Represents the property SpecificationVersion
        /// </summary>
        public virtual uint SpecificationVersion
        {
            get
            {
                return this._specificationVersion;
            }
            set
            {
                this._specificationVersion = value;
            }
        }

        /// <summary>
        /// Represents the property Status
        /// </summary>
        public virtual string Status
        {
            get
            {
                return this._status;
            }
            set
            {
                this._status = value;
            }
        }

        /// <summary>
        /// Represents the property StatusInfo
        /// </summary>
        public virtual ushort StatusInfo
        {
            get
            {
                return this._statusInfo;
            }
            set
            {
                this._statusInfo = value;
            }
        }

        /// <summary>
        /// Represents the property SystemCreationClassName
        /// </summary>
        public virtual string SystemCreationClassName
        {
            get
            {
                return this._systemCreationClassName;
            }
            set
            {
                this._systemCreationClassName = value;
            }
        }

        /// <summary>
        /// Represents the property SystemName
        /// </summary>
        public virtual string SystemName
        {
            get
            {
                return this._systemName;
            }
            set
            {
                this._systemName = value;
            }
        }

        /// <summary>
        /// Represents the property SystemPaletteEntries
        /// </summary>
        public virtual uint SystemPaletteEntries
        {
            get
            {
                return this._systemPaletteEntries;
            }
            set
            {
                this._systemPaletteEntries = value;
            }
        }

        /// <summary>
        /// Represents the property TimeOfLastReset
        /// </summary>
        public virtual System.DateTime TimeOfLastReset
        {
            get
            {
                return this._timeOfLastReset;
            }
            set
            {
                this._timeOfLastReset = value;
            }
        }

        /// <summary>
        /// Represents the property VideoArchitecture
        /// </summary>
        public virtual ushort VideoArchitecture
        {
            get
            {
                return this._videoArchitecture;
            }
            set
            {
                this._videoArchitecture = value;
            }
        }

        /// <summary>
        /// Represents the property VideoMemoryType
        /// </summary>
        public virtual ushort VideoMemoryType
        {
            get
            {
                return this._videoMemoryType;
            }
            set
            {
                this._videoMemoryType = value;
            }
        }

        /// <summary>
        /// Represents the property VideoMode
        /// </summary>
        public virtual ushort VideoMode
        {
            get
            {
                return this._videoMode;
            }
            set
            {
                this._videoMode = value;
            }
        }

        /// <summary>
        /// Represents the property VideoModeDescription
        /// </summary>
        public virtual string VideoModeDescription
        {
            get
            {
                return this._videoModeDescription;
            }
            set
            {
                this._videoModeDescription = value;
            }
        }

        /// <summary>
        /// Represents the property VideoProcessor
        /// </summary>
        public virtual string VideoProcessor
        {
            get
            {
                return this._videoProcessor;
            }
            set
            {
                this._videoProcessor = value;
            }
        }
    }
}
