#region Copyright Kayomani 2010.  Licensed under the GPLv3 (Or later version), Expand for details. Do not remove this notice.
/**
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or any 
    later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * */
#endregion
// <auto-generated>
// This code was generated by a tool.
// LinqToWmi.ClassGenerator Version: 1.0.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if  the code is regenerated.
// </auto-generated>
namespace Fap.Foundation.WMI_Prototypes
{
    using System;
    using System.Linq;
    using LinqToWmi.Core.WMI;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("LinqToWmi.ClassGenerator", "1.0.0.0")]
    public class Win32_BaseBoard
    {

        private string _caption;

        private string[] _configOptions;

        private string _creationClassName;

        private float _depth;

        private string _description;

        private float _height;

        private bool _hostingBoard;

        private bool _hotSwappable;

        private System.DateTime _installDate;

        private string _manufacturer;

        private string _model;

        private string _name;

        private string _otherIdentifyingInfo;

        private string _partNumber;

        private bool _poweredOn;

        private string _product;

        private bool _removable;

        private bool _replaceable;

        private string _requirementsDescription;

        private bool _requiresDaughterBoard;

        private string _serialNumber;

        private string _sKU;

        private string _slotLayout;

        private bool _specialRequirements;

        private string _status;

        private string _tag;

        private string _version;

        private float _weight;

        private float _width;

        /// <summary>
        /// Represents the property Caption
        /// </summary>
        public virtual string Caption
        {
            get
            {
                return this._caption;
            }
            set
            {
                this._caption = value;
            }
        }

        /// <summary>
        /// Represents the property ConfigOptions
        /// </summary>
        public virtual string[] ConfigOptions
        {
            get
            {
                return this._configOptions;
            }
            set
            {
                this._configOptions = value;
            }
        }

        /// <summary>
        /// Represents the property CreationClassName
        /// </summary>
        public virtual string CreationClassName
        {
            get
            {
                return this._creationClassName;
            }
            set
            {
                this._creationClassName = value;
            }
        }

        /// <summary>
        /// Represents the property Depth
        /// </summary>
        public virtual float Depth
        {
            get
            {
                return this._depth;
            }
            set
            {
                this._depth = value;
            }
        }

        /// <summary>
        /// Represents the property Description
        /// </summary>
        public virtual string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                this._description = value;
            }
        }

        /// <summary>
        /// Represents the property Height
        /// </summary>
        public virtual float Height
        {
            get
            {
                return this._height;
            }
            set
            {
                this._height = value;
            }
        }

        /// <summary>
        /// Represents the property HostingBoard
        /// </summary>
        public virtual bool HostingBoard
        {
            get
            {
                return this._hostingBoard;
            }
            set
            {
                this._hostingBoard = value;
            }
        }

        /// <summary>
        /// Represents the property HotSwappable
        /// </summary>
        public virtual bool HotSwappable
        {
            get
            {
                return this._hotSwappable;
            }
            set
            {
                this._hotSwappable = value;
            }
        }

        /// <summary>
        /// Represents the property InstallDate
        /// </summary>
        public virtual System.DateTime InstallDate
        {
            get
            {
                return this._installDate;
            }
            set
            {
                this._installDate = value;
            }
        }

        /// <summary>
        /// Represents the property Manufacturer
        /// </summary>
        public virtual string Manufacturer
        {
            get
            {
                return this._manufacturer;
            }
            set
            {
                this._manufacturer = value;
            }
        }

        /// <summary>
        /// Represents the property Model
        /// </summary>
        public virtual string Model
        {
            get
            {
                return this._model;
            }
            set
            {
                this._model = value;
            }
        }

        /// <summary>
        /// Represents the property Name
        /// </summary>
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }

        /// <summary>
        /// Represents the property OtherIdentifyingInfo
        /// </summary>
        public virtual string OtherIdentifyingInfo
        {
            get
            {
                return this._otherIdentifyingInfo;
            }
            set
            {
                this._otherIdentifyingInfo = value;
            }
        }

        /// <summary>
        /// Represents the property PartNumber
        /// </summary>
        public virtual string PartNumber
        {
            get
            {
                return this._partNumber;
            }
            set
            {
                this._partNumber = value;
            }
        }

        /// <summary>
        /// Represents the property PoweredOn
        /// </summary>
        public virtual bool PoweredOn
        {
            get
            {
                return this._poweredOn;
            }
            set
            {
                this._poweredOn = value;
            }
        }

        /// <summary>
        /// Represents the property Product
        /// </summary>
        public virtual string Product
        {
            get
            {
                return this._product;
            }
            set
            {
                this._product = value;
            }
        }

        /// <summary>
        /// Represents the property Removable
        /// </summary>
        public virtual bool Removable
        {
            get
            {
                return this._removable;
            }
            set
            {
                this._removable = value;
            }
        }

        /// <summary>
        /// Represents the property Replaceable
        /// </summary>
        public virtual bool Replaceable
        {
            get
            {
                return this._replaceable;
            }
            set
            {
                this._replaceable = value;
            }
        }

        /// <summary>
        /// Represents the property RequirementsDescription
        /// </summary>
        public virtual string RequirementsDescription
        {
            get
            {
                return this._requirementsDescription;
            }
            set
            {
                this._requirementsDescription = value;
            }
        }

        /// <summary>
        /// Represents the property RequiresDaughterBoard
        /// </summary>
        public virtual bool RequiresDaughterBoard
        {
            get
            {
                return this._requiresDaughterBoard;
            }
            set
            {
                this._requiresDaughterBoard = value;
            }
        }

        /// <summary>
        /// Represents the property SerialNumber
        /// </summary>
        public virtual string SerialNumber
        {
            get
            {
                return this._serialNumber;
            }
            set
            {
                this._serialNumber = value;
            }
        }

        /// <summary>
        /// Represents the property SKU
        /// </summary>
        public virtual string SKU
        {
            get
            {
                return this._sKU;
            }
            set
            {
                this._sKU = value;
            }
        }

        /// <summary>
        /// Represents the property SlotLayout
        /// </summary>
        public virtual string SlotLayout
        {
            get
            {
                return this._slotLayout;
            }
            set
            {
                this._slotLayout = value;
            }
        }

        /// <summary>
        /// Represents the property SpecialRequirements
        /// </summary>
        public virtual bool SpecialRequirements
        {
            get
            {
                return this._specialRequirements;
            }
            set
            {
                this._specialRequirements = value;
            }
        }

        /// <summary>
        /// Represents the property Status
        /// </summary>
        public virtual string Status
        {
            get
            {
                return this._status;
            }
            set
            {
                this._status = value;
            }
        }

        /// <summary>
        /// Represents the property Tag
        /// </summary>
        public virtual string Tag
        {
            get
            {
                return this._tag;
            }
            set
            {
                this._tag = value;
            }
        }

        /// <summary>
        /// Represents the property Version
        /// </summary>
        public virtual string Version
        {
            get
            {
                return this._version;
            }
            set
            {
                this._version = value;
            }
        }

        /// <summary>
        /// Represents the property Weight
        /// </summary>
        public virtual float Weight
        {
            get
            {
                return this._weight;
            }
            set
            {
                this._weight = value;
            }
        }

        /// <summary>
        /// Represents the property Width
        /// </summary>
        public virtual float Width
        {
            get
            {
                return this._width;
            }
            set
            {
                this._width = value;
            }
        }
    }
}