#region Copyright Kayomani 2010.  Licensed under the GPLv3 (Or later version), Expand for details. Do not remove this notice.
/**
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or any 
    later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * */
#endregion
// <auto-generated>
// This code was generated by a tool.
// LinqToWmi.ClassGenerator Version: 1.0.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if  the code is regenerated.
// </auto-generated>
namespace Fap.Foundation.WMI_Prototypes
{
    using System;
    using System.Linq;
    using LinqToWmi.Core.WMI;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("LinqToWmi.ClassGenerator", "1.0.0.0")]
    public class Win32_SoundDevice
    {

        private ushort _availability;

        private string _caption;

        private uint _configManagerErrorCode;

        private bool _configManagerUserConfig;

        private string _creationClassName;

        private string _description;

        private string _deviceID;

        private ushort _dMABufferSize;

        private bool _errorCleared;

        private string _errorDescription;

        private System.DateTime _installDate;

        private uint _lastErrorCode;

        private string _manufacturer;

        private uint _mPU401Address;

        private string _name;

        private string _pNPDeviceID;

        private ushort[] _powerManagementCapabilities;

        private bool _powerManagementSupported;

        private string _productName;

        private string _status;

        private ushort _statusInfo;

        private string _systemCreationClassName;

        private string _systemName;

        /// <summary>
        /// Represents the property Availability
        /// </summary>
        public virtual ushort Availability
        {
            get
            {
                return this._availability;
            }
            set
            {
                this._availability = value;
            }
        }

        /// <summary>
        /// Represents the property Caption
        /// </summary>
        public virtual string Caption
        {
            get
            {
                return this._caption;
            }
            set
            {
                this._caption = value;
            }
        }

        /// <summary>
        /// Represents the property ConfigManagerErrorCode
        /// </summary>
        public virtual uint ConfigManagerErrorCode
        {
            get
            {
                return this._configManagerErrorCode;
            }
            set
            {
                this._configManagerErrorCode = value;
            }
        }

        /// <summary>
        /// Represents the property ConfigManagerUserConfig
        /// </summary>
        public virtual bool ConfigManagerUserConfig
        {
            get
            {
                return this._configManagerUserConfig;
            }
            set
            {
                this._configManagerUserConfig = value;
            }
        }

        /// <summary>
        /// Represents the property CreationClassName
        /// </summary>
        public virtual string CreationClassName
        {
            get
            {
                return this._creationClassName;
            }
            set
            {
                this._creationClassName = value;
            }
        }

        /// <summary>
        /// Represents the property Description
        /// </summary>
        public virtual string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                this._description = value;
            }
        }

        /// <summary>
        /// Represents the property DeviceID
        /// </summary>
        public virtual string DeviceID
        {
            get
            {
                return this._deviceID;
            }
            set
            {
                this._deviceID = value;
            }
        }

        /// <summary>
        /// Represents the property DMABufferSize
        /// </summary>
        public virtual ushort DMABufferSize
        {
            get
            {
                return this._dMABufferSize;
            }
            set
            {
                this._dMABufferSize = value;
            }
        }

        /// <summary>
        /// Represents the property ErrorCleared
        /// </summary>
        public virtual bool ErrorCleared
        {
            get
            {
                return this._errorCleared;
            }
            set
            {
                this._errorCleared = value;
            }
        }

        /// <summary>
        /// Represents the property ErrorDescription
        /// </summary>
        public virtual string ErrorDescription
        {
            get
            {
                return this._errorDescription;
            }
            set
            {
                this._errorDescription = value;
            }
        }

        /// <summary>
        /// Represents the property InstallDate
        /// </summary>
        public virtual System.DateTime InstallDate
        {
            get
            {
                return this._installDate;
            }
            set
            {
                this._installDate = value;
            }
        }

        /// <summary>
        /// Represents the property LastErrorCode
        /// </summary>
        public virtual uint LastErrorCode
        {
            get
            {
                return this._lastErrorCode;
            }
            set
            {
                this._lastErrorCode = value;
            }
        }

        /// <summary>
        /// Represents the property Manufacturer
        /// </summary>
        public virtual string Manufacturer
        {
            get
            {
                return this._manufacturer;
            }
            set
            {
                this._manufacturer = value;
            }
        }

        /// <summary>
        /// Represents the property MPU401Address
        /// </summary>
        public virtual uint MPU401Address
        {
            get
            {
                return this._mPU401Address;
            }
            set
            {
                this._mPU401Address = value;
            }
        }

        /// <summary>
        /// Represents the property Name
        /// </summary>
        public virtual string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }

        /// <summary>
        /// Represents the property PNPDeviceID
        /// </summary>
        public virtual string PNPDeviceID
        {
            get
            {
                return this._pNPDeviceID;
            }
            set
            {
                this._pNPDeviceID = value;
            }
        }

        /// <summary>
        /// Represents the property PowerManagementCapabilities
        /// </summary>
        public virtual ushort[] PowerManagementCapabilities
        {
            get
            {
                return this._powerManagementCapabilities;
            }
            set
            {
                this._powerManagementCapabilities = value;
            }
        }

        /// <summary>
        /// Represents the property PowerManagementSupported
        /// </summary>
        public virtual bool PowerManagementSupported
        {
            get
            {
                return this._powerManagementSupported;
            }
            set
            {
                this._powerManagementSupported = value;
            }
        }

        /// <summary>
        /// Represents the property ProductName
        /// </summary>
        public virtual string ProductName
        {
            get
            {
                return this._productName;
            }
            set
            {
                this._productName = value;
            }
        }

        /// <summary>
        /// Represents the property Status
        /// </summary>
        public virtual string Status
        {
            get
            {
                return this._status;
            }
            set
            {
                this._status = value;
            }
        }

        /// <summary>
        /// Represents the property StatusInfo
        /// </summary>
        public virtual ushort StatusInfo
        {
            get
            {
                return this._statusInfo;
            }
            set
            {
                this._statusInfo = value;
            }
        }

        /// <summary>
        /// Represents the property SystemCreationClassName
        /// </summary>
        public virtual string SystemCreationClassName
        {
            get
            {
                return this._systemCreationClassName;
            }
            set
            {
                this._systemCreationClassName = value;
            }
        }

        /// <summary>
        /// Represents the property SystemName
        /// </summary>
        public virtual string SystemName
        {
            get
            {
                return this._systemName;
            }
            set
            {
                this._systemName = value;
            }
        }
    }
}
